### ISSUE TITLE
Pressure curve point deletion non-obvious; hard to grab

### ISSUE THREAD

**Issue by GreenReaper** [callaa/Drawpile#114]
Users had great ease creating pressure curve points, but found it harder to get rid of them; they tried double clicking and dragging them together and it took about half a minute for them to figure out that they could drag them off. Maybe moving together and double-click could be removal options as well.

It was also hard for users on a high-DPI tablet to grab the pressure points. Right now you have to click exactly on the pressure point. It would be useful if their size/capture area was expanded, as it is not usually necessary to have many points close to each other.

A quick way to reset the pressure curve would also be useful. Context menu? Could have "add", too.

**Comment by callaa** [comment]
I increased the point handle size and added a context menu for removing points and resetting the entire curve to default.
