### ISSUE TITLE
Box selection icon unclear, location confusing

### ISSUE THREAD

**Issue by GreenReaper** [callaa/Drawpile#118]
Users couldn't find the box selection/rectangular marquee tool because they expected it to be a box with more clearly dashed or dotted lines. In fact, it *is* dotted, but this can be very hard to see, especially on a high-DPI screen.

The icon is also immediately before tools which directly modify the image. Some users selected the box creation tool instead when trying to select because they were looking for something which came after those tools.

**Comment by callaa** [comment]
A new icon theme is now in place. Although I'm not sure if the new icon is any clearer, it is at least now grouped with other selection and non-destructive tools.
