### ISSUE TITLE
Selection tool does not meet user expectation of being a marquee

### ISSUE THREAD

**Issue by GreenReaper** [callaa/Drawpile#122]
The selection tool doesn't work as users expected; the current functionality of copies, cuts, and fills is useful, but only part of what's typical.

Users are used to selections acting as a marquee which masks off the effect of other tools, and which stays selected until they go to Edit/Deselect, or made another selection.

Users also expect to be able to move the data within the selection on the current layer by dragging from inside it. (Instead, it just moves the selection outline.)

There might be hover handles to stretch the selection as well, though there are cases in which the user might also want to resize the selection; perhaps modifier keys are needed to distinguish actions.

**Comment by callaa** [comment]
Dragging a selection will now automatically move the contents too. (Related issue: #190)
