### ISSUE TITLE
Can't remove assigned keyboard shortcuts, no way to reset shortcuts to default, misc. shortcut things (Windows 7)

### ISSUE THREAD

**Issue by chetchaka** [callaa/Drawpile#167]
In Drawpile's preferences, there is no keyboard key assigned to deleting a given shortcut key from its assigned spot, nor is there a button / option that lets you reset these bindings back to their defaults. There is also no configuration file outside of the main program that allows these to be changed.

Relatedly, as a feature request, could the shortcuts assigned to Shift, Alt, Ctrl, and Space be modifiable as well? Possible modifications include: [Disabled], Rotation or Pan (hold button and drag with pen / mouse), Color Picker, Hold key for last-used tool
I could foresee a conflict with Alt-based shortcuts (such as show/hide chat) if Alt were modifiable.

**Comment by callaa** [comment]
You can clear a shortcut by pressing a modifier key like Control, then deselecting the item. I'm using Qt's standard shortcut selection widget and unfortunately it doesn't have a Clear button feature. (I looked at the source code and there is a comment: `// TODO: add clear button`)
I can, however, make a custom widget that adds the missing clear button.

The canvas shortcut keys are only used together with mouse/pen, so they shouldn't conflict with the other shortcuts.
I'll take a look if it would be easy to make them configurable.
