### ISSUE TITLE
Can't delete points on input pressure curve (Windows 7)

### ISSUE THREAD

**Issue by chetchaka** [callaa/Drawpile#168]
You can add as many points on the pressure curve as you want, but they cannot be removed, and they are automatically saved. Mis-clicking can create more points on the curve than one would like, and make it harder to modify! A way to reset the curve to default with only one point should be implemented.

**Comment by callaa** [comment]
There are actually two ways to remove points from the curve, but they're a bit unintuitive: dragging a point out of the widget will remove it. The other way is to click on a point to select it, then press backspace.
Others have had the same difficulty discovering this functionality: #114

Perhaps adding a context menu with "Remove selected point" and "Reset to default" actions might help?

**Comment by callaa** [comment]
I added a context menu from which the selected point can be removed and the whole curve reset.
