### ISSUE TITLE
Tablet PC Support (Surface Pro 3)

### ISSUE THREAD

**Issue by redrodent** [callaa/Drawpile#169]
Tablet PC pen pressure not detected by Drawpile.

I recently acquired a Surface pro 3, and was super excited to try out all my art applications, including Drawpile on it. I quickly learned that since Microsoft and WACOM parted ways, the Surface Pro 3 will not run "WACOM feel" drivers. 

What this means for me is that my computer is a tablet PC and won't get along with many art applications. That is, unless I hook up an Intros to it or something. Drawpile is no different, and won't recognize my computer's pressure sensitive stylus as pressure sensitive. 

Are there any plans on integrating support for tablet pcs in the future?

**Comment by callaa** [comment]
Drawpile currently relies entirely on the tablet support provided by Qt. So, the options are to either wait for Qt's tablet support to improve or to add platform specific code to handle the cases not supported by Qt. (I think Krita has done the latter.) Qt is currently adding support for Windows RT, and many of those devices have stylus digitizers, so there is still hope.

As for adding platform specific code, that is something I am unable to do right now, as I don't have a tablet PC to develop and test with. The Surface Pro 3 does look like it would be great for digital painting, so supporting it is certainly something I would like to do.

On a related note, I am planning on adding an alternative tablet optimized UI. This is still in planning stage, but will be one of the major features for version 2.0.

**Comment by callaa** [comment]
I came across this: http://surfaceproartist.com/blog/2014/6/20/n-trigs-wintab-driver-update-now-available-for-download

Have you tried installing the n-trig drivers rather than the wacom ones?
