### ISSUE TITLE
Public session list

### ISSUE THREAD

**Issue by callaa** [callaa/Drawpile#170]
A public list for announcing and finding open drawing session directly from the application:
[Design document](https://github.com/callaa/Drawpile/wiki/Session-listing)

Opinions? Can anyone spot any security problems with the API as proposed?

**Comment by schoerg** [comment]
Maybe the server should check if
```
"host": "host address"
```
is really originating from that host. Also, what if in the host address a private IP is entered like in NAT situations? Will the IP be overwritten by the client to the external IP or is this a job for the server?

**Comment by callaa** [comment]
If the host field is left blank, then the originating IP will be used. The user can specify the host so sessions hosted on remote servers can be announced. I suppose there is a risk that someone might post someone else's IP to drive unwanted traffic to them, but that threat is probably quite minimal.

I just remembered that I should add a field for the port as well. Having it separate from the host address should make validation a bit simpler.

**Comment by schoerg** [comment]
Ok, so when the client is behind a NAT he shouldn't enter a host address in order to let the server decide on the IP?

**Comment by callaa** [comment]
The application should handle this automatically. If the "use built-in server" option is selected, then the app should leave the host field empty. Otherwise, it should use the remote server address. If *that* address is a local one, then I'm not sure what to do.

Perhaps it would be better to have the server be in charge of making the announcement? Then the public listing server could then always use the request's originating IP. Although even here could be weird edge cases if the server has multiple IP addresses.

**Comment by schoerg** [comment]
I don't think that local IPs are a problem if the announcenment server is also in the same network.

**Comment by callaa** [comment]
Yes, that is true. However, I think a publicly accessible announcement server will be the most (or at least fairly) common use case.

The possible cases are:

* Public announcement server (A-server)
   * Session hosted on a builtin drawpile server (D-server) visible to the Internet
   * Builtin D-server behind a NAT firewall
   * Remote D-server visible to the Internet
   * Remote D-server on the same internal NAT firewalled network
   * Remote D-server on a private network (e.g. Hamachi.)

* Private A-server
  * Session hosted on the same network
  * Remote D-server on a private network

First, we can discount the last case (private network,) since there is now way to make it work. The A-server should catch the private host IP and return an error.

Automatically getting the server's public IP will fail in the Private-A server+Host On Same Network case, but work in the other cases, with the exception of Remote Server On Private Network, since port forwarding might not actually be set up for that server. Also, it will work unreliably in the Public Server With Multiple IP Addresses case.

Using the client specified remote host address will work if that address is public. (If the internal server is publicly visible, then the user should use its public address when connecting)

I'm still leaning towards using origin IP when using a built-in server and user specified address when using a remote server. As long as the A-server validates the host address properly, this should result in the most predictable behavior. (Also, it allows the use of DNS names rather than IP addresses.)

**Comment by schoerg** [comment]
Something I though of as I know some game protocols do it: They have 2 IP addresses, one internally one externally, which maybe could help.

**Comment by callaa** [comment]
Upon further consideration, having the server handle the announcement might be a better idea after all. The original user can leave the session, but the listing should still remain up as long as the session exists, and only the server knows the full session lifecycle.

In the unusual case where the server's IP address (as seen by the listing server) isn't the right one for users to connect to, the server administrator can specify the address manually.

If the admin is concerned about clients having the server make HTTP requests to arbitrary addresses, the allowed listing servers can be whitelisted.
