### ISSUE TITLE
the new annotation tool is terrible

### ISSUE THREAD

**Issue by EvilKitty3** [callaa/Drawpile#172]
Each time i edit the text, the box shrinks to its default size, ignoring the text thats too big to be all viewed. Will this be fixed or am i missing something? Pls fix it D: It was just fine in version 0.9.5 ...

**Comment by callaa** [comment]
Funny timing, I just pushed a fix for this :) There were a lot of regressions in the current, so I'll probably release the next version in a few days.

**Comment by EvilKitty3** [comment]
yey thank you! Looking forward! Totally loving this program with my friend by the way :D Been using OpenCanvas1 for ages but DrawPile replaced that like instantly. Any place to make suggestions perhaps?

**Comment by callaa** [comment]
Thanks! If you have ideas for new features or other enhancements, you can use this issue tracker to make feature requests. Bug reports too, of course. There is also a feature brainstorming section on the [roadmap wiki page](https://github.com/callaa/Drawpile/wiki/Roadmap) for low priority nice-to-have things and ideas that still need further planning.
