### ISSUE TITLE
After inserting a picture from the clipboard, tool doesn't change back to the one used before

### ISSUE THREAD

**Issue by schoerg** [callaa/Drawpile#176]
Example:

I insert a picture from the clipboard, my input tool is now "Select (Rectangular)". I think it should switch back to the tool you used before, after inserting the picture, it should switch back after you pressed the left mouse button to submit the picture.
I think this was the case in a previous version, I am not sure.

**Comment by callaa** [comment]
I don't think this feature is present in any version to date (at least I don't recall implementing it), but it does sound like natural and expected behavior.
