### ISSUE TITLE
(wild) feature request : Drawpile - the first truly collaborative animation software!!

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#180]
What if Drawpile had the ability to store animation frames, each animation frame contains a set of layers.
This way multiple users could work on an image sequence together. Annotate frames and chat while animating.
During a drawing session, each of the users can play the animated sequence so far and switch between frames.

The animation frames list window:
A horizontal window that shows all current animation frames in thumbnails or shows a thumbnail of a hovered on frame by mouse.

- could allow for users to switch between frames to work on. 
- Allow for users to create new frames, move frames around
- Indicate on which frame the user is working on.
- Indicate on which frames the other users are working on

The animation preview/export window could work in two possible ways
-When playing the animation sequence, drawpile could make a temporary snapshot of all the frames and simply play them in a new window. Then when the animation preview window/mode is closed, drawpile could delete the temporary frame files (tmp folder?).

-Pause all activity for local user and just play the frames in the work area window.

Export options:
- Export gif file (useful for small sprites to go in games)
- Export image sequence (PNG)

Possible technical problems:
- Huge files being created
- Others I cant think of as of now, complexity of the software would fly through the roof.
It is certainly a very ambitious thing to develop. Maybe drawpile version 99999 (its over 9000!!)
:)

=========================================

Update 1- Initial design proposal:

I think that if you want to use the layers data to animate, you will have to create an alternative way to edit/manage the layers in Drawpile.

A new X-sheet dock is needed to address the animation workflow!

I put down some time to create a proposal design and a mockup. Please let me know what you think and if some stuff in there is unclear. :)
Click for full screen.

![xsheetindrawpile](https://cloud.githubusercontent.com/assets/6495061/6405150/a402cf9e-be28-11e4-8438-8707bd95231a.png)

Under the hood x-sheet dock is just managing the same layers that are in the layer's dock. It's just doing it in a radical new way!
>key pose drawings can occupy frame ranges. So When you extend a drawing to occupy three frames instead of one, the x-sheet dock technically creates two new copies/clones of that layer above or bellow it (depending on which of the two arrows the user dragged)
>when playing from xsheet, mypaint can operate in solo layer view: like the "hide" feature, but hides all other layers except the selected one.
Onion skin mode: hide all layers above the selection and show the ones below it with adjusted opacity

note for the mockup proposal: a frame that doesnt contain a drawing yet could be just the number of the frame, but color coded.. or it could be a symbol [-] or [0]  or something.
The +(add) MENU should say "add drawing" instead of "add frame". Replace the word "frame" with "Drawing" there. I will update it later if you like the proposal

The ability to scribble annotations is very very nice, but not a must have- considering it would be complicated to implement and sync between users.

>Copying and pasting+insert drawings could be done with the right click menu.
>Deleting a drawing should move all the drawings bellow it upwards- filling its spot, so as not to have a missing drawing in its place.
>moving a drawing in the x-sheet could be done by just dragging it.

=============================

Layer tagging:

another idea for the implementation:
If you add the ability to attach metadata to layers, you might be able to tell drawpile to treat some of the existing layers as animation frames, others - as a background element that is not affected by the x-sheet.

Taking it way further:
-instead of duplicating a layer to hold a drawing longer, drawpile could have a variable for time length  (for how many frames should I keep this layer drawing) attached to the layer. This would greatly increase how long the animations could be in it.
A layer  could contain the metadata of time range in which it exists - instead of being duplicated by the software a bazillion times.

-Another metadata attached to the layer could tell the x-sheet to treat it as a background element that is behind the animation.

-if variables in layers tell the x-sheet when to play layers and for how long, then managing your animation with the x-sheet doesnt have to move the layers around in the layer docker. 

-best of all you can make both the layer and the x-sheet dockers useful for the animation pipeline. A tag attached to layers could tell the Layer docker to not show all of it's frames
 
![path10320](https://cloud.githubusercontent.com/assets/6495061/6411961/9e9715b6-be86-11e4-809b-52b25a2cebd7.png)

=============================

Notes by callaa:
>The features needed to support this kind of work flow would be:
>
>Animation preview window that cycles through the layers (like Animation->Playback in GIMP)
>"Duplicate layer" button (been meaning to implement this anyway.)
>Export to animated GIF
>Export individual layers (this already exists in a way: ORA files are actually zip files containing the >layers in PNG format)
>Solo layer view: like the "hide" feature, but hides all other layers except the selected one.
>Onion skin mode: hide all layers above the selection and show the ones below it with adjusted opacity
>The simplified approach has the downside that it would only be usable for fairly short animations. >Currently, the maximum number of layers that can be created is limited to 255 per users (this is a >protocol limitation.) Although, even then I can image it might be very handy for low-FPS animated >storyboards!

**Comment by schoerg** [comment]
As a workaround you could use layers and combine the frames manually afterwards.

**Comment by blurymind** [comment]
yeah, but its not easy to work that way :)
No easy playback and onion skinning.

**Comment by callaa** [comment]
A fully featured animation editor might be bit out of scope for this project, but simple support for animations using layers as frames (like in the GIMP) would be possible to implement.

The features needed to support this kind of work flow would be:

* Animation preview window that cycles through the layers (like Animation->Playback in GIMP)
* "Duplicate layer" button (been meaning to implement this anyway.)
* Export to animated GIF
* Export individual layers (this already exists in a way: ORA files are actually zip files containing the layers in PNG format)
* Solo layer view: like the "hide" feature, but hides all other layers except the selected one.
* Onion skin mode: hide all layers above the selection and show the ones below it with adjusted opacity

The simplified approach has the downside that it would only be usable for fairly short animations. Currently, the maximum number of layers that can be created is limited to 255 per users (this is a protocol limitation.) Although, even then I can image it might be very handy for low-FPS animated storyboards! The upside is that these changes are relatively minor and could be done during the 0.9.x or 1.x development cycle, whereas a building a proper animation editor would warrant a major development cycle for itself.

**Comment by blurymind** [comment]
Some features to compliment layers as animation feature:

The approach noted by calla is spot on and it might work great!!
I want to add some complimenting features to it:

-in this case having "solo" layer mode have "onion skinning" would be a must have :)
--colorizing in red previous and in blue next layers of onion skin (similar to pencil2d)
--setting onion skin range (1-5)
--setting onion skin forward,backward and both

-Having layer folders and cycling between layer folders and/or top of hierarchy layers - would allow the artists to at least separate sketch layer, ink and color layer of each frame. Working non destructively and not on a single layer per frame!

- setting playback frame range- for playback and for exporting
-setting playback speed- frames per second (framerate)- for playback and exporting

-gmic colorize plugin will greatly speed up frame coloring! (already requested)
-line smoothing brush mode will help with inking greatly (already requested)

**Comment by callaa** [comment]
Good ideas.
I just committed the implementation for the LayerCopy command, which is the only protocol change needed. I'll probably implement most of the features during the next release or two, but with LayerCopy out of the way, this feature can be worked on even during 1.x.

Layer hierarchy is something I'm going to leave for later, though, since it requires rather extensive protocol changes, which is something I don't want to do before the big refactoring I've planned for 2.0.

**Comment by blurymind** [comment]
I think that if you want to use the layers data to animate, you will have to create an alternative way to edit/manage the layers in Drawpile.

A new X-sheet dock is needed to address the animation workflow!

I put down some time to create a proposal design and a mockup. Please let me know what you think and if some stuff in there is unclear. :)
![xsheetindrawpile](https://cloud.githubusercontent.com/assets/6495061/6405150/a402cf9e-be28-11e4-8438-8707bd95231a.png)

**Comment by blurymind** [comment]
A note on length of animation being limited:

In most cases of classic animation- it is being animated on twos (12 frames per second or even less). So 255 frames = 21 seconds of animation.

This is more than enough for a shot in a scene. When there is a collaboration on a shot between animators- this is more than enough. If you wanna work on another shot, just join another session. 

An animated walk cycle requires 8 frames usually.
so Drawpile could also be used for collaborative animation of sprites for games. :)

**Comment by blurymind** [comment]
another idea for the implementation:
If you add the ability to attach metadata to layers, you might be able to tell drawpile to treat some of the existing layers as frames, others - as a background.

Taking it way further:
- instead of duplicating a layer to hold a drawing longer, drawpile could have a variable for time length  (for how many frames should I keep this layer drawing) attached to the layer. This would greatly increase how long the animations could be in it.
A layer  could contain the metadata of time range in which it exists

-Another metadata attached to the layer could tell the x-sheet to treat it as a background element that is behind the animation.

-if variables in layers tell the x-sheet when to play layers and for how long, then managing your animation with the x-sheet doesnt have to move the layers around in the layer docker.

**Comment by callaa** [comment]
I added a new [wiki page](/callaa/Drawpile/wiki/Help%3A-Animation) documenting the upcoming animation features.

**Comment by blurymind** [comment]
This is an awesome start!! :)
I really wish we could keep the current layer dialog design as it currently is - without cluttering it with animation features. Thus why I proposed a separate x-sheet dialog to manage layers in an animation mode. Layer tagging to show all the layers of a sequence as one entry in the layers dialog. Double clicking it cloud switch the layer dialog to the X-sheet dialog automatically.

I am still very happy that it is on the map- so whatever design you go with - being able to collaborate with others to do an animated sequence would be an amazing new feature. I dont know any other single animation software that does that at the moment. Or has done it ever.

**Comment by callaa** [comment]
Yes, for complicated animations having the separate x-sheet feature would be better than jamming everything into the layer dock. But, since that would require protocol changes, I'm leaving it for until after 2.0, if its going to be implemented.

After the basic features are done, we'll see if Drawpile is suitable for animation work in practice and hopefully feedback from real world use will guide the development of the more advanced features.

**Comment by blurymind** [comment]
I do animation and know a few traditional animators that would be quite interested to try it. :)
Cant wait.

Thank you so much for developing drawpile. It's such a gift to the community.

**Comment by blurymind** [comment]
In solo layer view mode - it would be good if we disable the checkerboard drawing for alpha channel. Its hard to see

**Comment by callaa** [comment]
I think I'll add a setting to choose between the checkerboard background or a solid color. Another option might be to always draw the bottom-most layer, even in Solo mode. (Perhaps Solo+Bg mode?)

**Comment by blurymind** [comment]
The second option would be more useful to animators :)

**Comment by callaa** [comment]
Some progress :) Onionskin view mode is now implemented (though the view depth is not yet configurable), as is the animation exporter. The same exporter is used for recordings and layer based animations, so future improvements will benefit both. Now the only major thing missing from the basics is the flipbook/animation preview window.

**Comment by blurymind** [comment]
You are made of awesome! :) 
Onion skin is a very very important part of the workflow.
The basic foundations for flipbook style animation are almost there.

**Comment by callaa** [comment]
The flipbook window is now implemented.
Also, I added support for opening animated GIFs (or any animated image format supported by Qt) so each frame is loaded into a layer. GIF export still needs to be done though.

**Comment by blurymind** [comment]
I am getting tempted to grab it from github. Cant wait for the next release :D

**Comment by blurymind** [comment]
I grabbed a copy from github! :)

I know its not finished. here are some suggestions:

In onion skin mode or any of the other animation layer modes:

-it should reduce previous frame opacity depending on how far behind the currently active frame is. Right now it seems to be setting the same opacity to all previous frames
-it would be nice if it colored in a red tint previous frames and in a blue one frames after the active one.

example:
 
![001onionskin](https://cloud.githubusercontent.com/assets/6495061/7098381/78241d2e-dfe8-11e4-803a-11e16f42fac5.png)


-hide layer modes (normal,multiply,etc) list, as it doesnt do anything when in animation modes
-Hide layer opacity slider or re-purpose it to do something else
-Add shortcut keyboard keys to flip between layers
-Option to control how many previous and how many forward frames to show in onion skin.

On the Flipbook player: It is awesome and works really well!! 
I found it a bit difficult to get to the play button when the canvas is too big - it was outside the screen. I couldnt resize its window. But I got to it by mvoing it when holding alt key.

**Comment by blurymind** [comment]
btw, here is a script to build it from github - for Arch linux users:
https://aur.archlinux.org/packages/drawpile-git/

I made it for anyone who wants to test out the bleeding edge :)

**Comment by callaa** [comment]
Currently, the opacity falloff is linear. A cubic falloff might look better though. Here's a comparison:

![onionskin_falloff](https://cloud.githubusercontent.com/assets/464576/7105294/641dca90-e11a-11e4-9865-6cd7e7f638da.png)

The picture on the left is how it works now: each layer's opacity is reduced by the same amount. On the right, the opacity of reduction increases the further the layer is from the selection.

I'll have to think about the color tinting mode. Unlike the opacity adjustment, there is no pre-existing functionality that could be adapted, so implementing it (in a non-hackish way) is a bit more work. I do have an idea how it might work under the hood, which might later be expanded into a general purpose layer effects feature.

I will not change the layer controls yet, since then I would have to create separate modes for animation and still image editing. If the animation use cases becomes popular enough to warrant the extra effort, I'll implement the x-sheet layer organizer.

**Comment by blurymind** [comment]
The cubic falloff (on the right) does look much much better. It is easier to work with.

**Comment by blurymind** [comment]
It would be great of there is a quick keyboard shortcut that opens the flipbook window and plays it automatically.

**Comment by blurymind** [comment]
another suggestion - to make it easier to add inbetween frames:
When creating a new layer (when in any of the animation view modes), create the new layer above the currently selected layer. 
You can alternatively do it via a new command called "insert new layer above current".

Drawing inbetweens and breakdowns is very important for a walk cycle for example. Right now you have to create a new layer and drag it down in order to use it as an inbetween.

Also onion skinning of frames that are ahead of the currently active one will help a lot too - but then you would need to color code them somehow.

**Comment by blurymind** [comment]
Tried the newest from github. Now you can resize the flipbook window, but the image gets squashed irregularly 

![screenshot_2015-04-16_09-31-42](https://cloud.githubusercontent.com/assets/6495061/7175308/adebd29e-e41b-11e4-9ecb-bd5bcba3dd21.png)

**Comment by callaa** [comment]
Whoops! Looks like I forgot the aspect ratio flag.
The onionskin above/below layer counts are now configurable and the color tint mode is implemented.

**Comment by callaa** [comment]
I added an "insert layer" action to the layer context menu. I also took the opportunity to do some refactoring here and merged the LayerCreate and LayerCopy commands into a single more versatile command, so layer insertion can now be done with just one command, rather than add layer + reorder. (This is, unfortunately, a protocol compatibility breaking change.)

**Comment by blurymind** [comment]
I am just playing with it as we speak!!
This is absolutely fantastic :)

It's incredible how quickly you add these features. Other open source animation software developers take months. You whip them up in the matter of days!  

The bit about the protocol is unfortunate, but I guess you have to break some eggs to make an amazing omelette :)

Ok, continuing with the suggestions:
- The tint  and the forward frames features are kind of hidden by default. Lets have them enabled by default. 4 frames forward and 4 frames backward is a nice default to have!  
- The insert layer feature works beautifully, but I couldnt find it at first - because I expected that it would also be at the menu where the "new layer" command is.
-I dont think I will ever use  "solo" and "onion skin" without the BG while working - because that checkerboard pattern is really distracting. But I guess that it would be useful to see the alpha when previewing the animation - when there is no bg. This is especially important if Drawpile is used to create animated sprites for games. You already have that feature nailed! I think that Drawpile's collaborative nature can really make it shine at Game Jam events.

One suggestion I could make on the without-BG modes is to add the ability to over ride the alpha checkerboard also to the animation settings (for the canvas window). You already have it at the export settings.
![screenshot_2015-04-17_14-48-31](https://cloud.githubusercontent.com/assets/6495061/7201590/9290715c-e511-11e4-8453-988add4ba2af.png)

- Later on, if we get an x-sheet, it would be nice to have a button that opens up the preferences window straight in the animation tab. Sort of how maya has it.

**Comment by blurymind** [comment]
- You could add both the animation layers setting and the Background setting (from the export animation window) to the flipbook window. Those would be useful there :)
![screenshot_2015-04-17_14-58-08](https://cloud.githubusercontent.com/assets/6495061/7201662/76158106-e512-11e4-934c-58e5db63a1bd.png)

**Comment by blurymind** [comment]
On the "Onion skin + BG" and the "Solo+BG" view options, I can already disable the Visibility of the BG by toggling it's layer visibility off:
![screenshot_2015-04-17_15-06-52](https://cloud.githubusercontent.com/assets/6495061/7201746/73a46418-e513-11e4-80fd-92ac93ea509f.png)

So perhaps you dont need to have "Onion skin (without bg)" and "Solo (without bg)" options. Only the ability to tell Drawpile which is the starting layer and which is the ending layer  at the flipbook window. From there on it could just treat layers bellow the starting layer as BG layers.

 just an idea :)

**Comment by callaa** [comment]
Some more changes:

* Onionskin defaults are now 4 below and above and tint enabled
* The "+ BG" modes are replaced with a "use background layer" setting, which is enabled by default
* Layer switching shortcuts Ctrl+Up and Ctrl+Down. These can be customized via the preferences dialog.

**Comment by blurymind** [comment]
Nice work! It is now a much cleaner implementation! :)

**Comment by blurymind** [comment]
I think this is ready now to be used for simple animation loops (video game sprites) and also for pencil tests where there is no dialogue.

For acting type animation you would need to be able to attach a sound waveform to the layers dialog and have it play in the flipbook window.  That sound waveform preview in the layers or x-sheet is required in order to see where to put keyframes with specific syllables/actions:
![layerswaveform](https://cloud.githubusercontent.com/assets/6495061/7219925/d7b78b7c-e6be-11e4-9075-224525eaafc2.png)
One thing that adds complication to it is that it's vertical scale is being affected by the frames per second value. 

Sites like 11 second club could potentially fall in love with drawpile if we had the sound feature. 
http://www.11secondclub.com/
Not sure how it would work with the network protocol though. The users could load the waveform locally themselves. 

Maybe that could be added later on - in a future x-sheet dialog. You already have an incredible 1st animation version shaped up that is already pretty useful!

So congratulations on that. Beautiful work!

**Comment by blurymind** [comment]
it would be nice to also be able to import an image sequence - but that is an extra I guess.

**Comment by blurymind** [comment]
One way to be able to sketch, clean up and ink a drawing without the need to use multiple layers is to do it like tvpaint - 
https://vimeo.com/57043308  (see at 5:28)

It has 4 compositing inks that can be erased individually - red, cyan, green and black.
The user sketches in one color (cyan), then for the second pass sketches with another color(black) over the old color. Then with a single click of a button, he erases the first color that is underneath (cyan) and gets a clean drawing.
If he wants to further refine the drawing, the artist turns the cleaned sketch he has (black ink) into a another color (cyan) again. Then repeats the process.
![tvpaintrgbpanelsketch](https://cloud.githubusercontent.com/assets/6495061/7229931/cbd98ab8-e771-11e4-82bf-d5fe5d954d58.png)

This is really a fantastic way to work on a single layer and mimics the traditional animator workflow as well! In traditional animation animators sketch with the cyan pencil, then sketch with the black pencil on top of the cyan. Then erase the cyan pencil with an eraser that only affects it:
![screenshot_2015-04-20_15-31-22](https://cloud.githubusercontent.com/assets/6495061/7229996/7170a11e-e772-11e4-982d-a95abf8e3c19.png)

It will empower drawpile to do cleaned up and nice looking animation way before you implement animation layers.

I am not sure how easy it would be for you to get a color by it's rgb value on a layer and erase it, or colorize it to another rgb value. Tvpaint has 4 colors to do this workflow, but you can really get away with two - cyan and black.

**Comment by blurymind** [comment]
updated above post to add an implementation design idea. :)

Note that this can also be very very useful not just for animation work, but for sketching!

**Comment by blurymind** [comment]
One way to be able to sketch, clean up and ink a drawing without the need to use multiple layers:
![tvpaintrgbpanelsketch](https://cloud.githubusercontent.com/assets/6495061/7229931/cbd98ab8-e771-11e4-82bf-d5fe5d954d58.png)

I made a feature request here:
https://github.com/callaa/Drawpile/issues/191 - clean up Pencil sketch layer command
(moved it out to another issue entry)

This will be very beneficial to the one layer sketch animation design that drawpile will have for what I assume is a long time. We need a way to clean up the animation and this is the simplest solution.
Its always a sketch at the start. :) If you want drawpile to be able to make more polished results this is the way to go imo.

**Comment by blurymind** [comment]
"select layer bellow" and "select layer above" should be renamed to "next frame" and "previous frame".
Right now it is very hidden from the animators as a feature and it shouldnt. Make the command available somewhere in the menus, not only at the shortcuts - so as to communicate to the user of its existance.

Default keyboard shortcut to go to previous/next frame:
Since the right hand is holding the stylus, and the animator tends to flip back and forth a lot between frames, it is best to have the flipping happen with the left hand.
So keys on the left hand side of the keyboard are preferable.

I have mine set to 
shift+z = go to previous frame
shift+x = go to next frame
shift+space = open flipbook window 
space= play flipbook window

It would be better if the flipbook window could be set to start playing automatically when you open it.

Remember that when animating, you would be doing these things over and over again. Animators who try drawpile need to feel right at home.
Right now go to next and previous frame commands are not easy to discover because of their name and because they are not available in the menus, and because they dont have any keys set to them by default.

**Comment by blurymind** [comment]
Another low hanging fruit usability feature suggestion:
When creating new layers in solo/onion skin mode, have drawpile automatically name them "Frame <# of the frame>" instead of "Layer <# of the layer>".

Currently the "# of the layer does not even correspond to the number of the frame that it represents when you open the flipbook.

**Comment by callaa** [comment]
I added the layer up/down shortcuts to the menu (tools->shortcuts submenu. Not really optimal, but it was the best place without creating new menus) The shortcuts actually do have default hotkeys: ctrl+up and down. Being able to operate them with just one hand is a good idea though, so I changed them to shift+z and shift+x, as you suggested.

Regarding the naming, since frames are not a first class concept in Drawpile, I don't want to call layers frames.

I changed the flipbook dialog to autoplay when shown. Space bar is already used for dragging and rotating, so I don't want to overload it any further by default. When the flipbook is open, the play button is highlighted by default, so there space bar will toggle play/pause.

Regarding the layer numbers, the numbers should match up with the frames as long as "Layer 1" is the name of the first frame. Of course, they will quickly go out of sync when layers are inserted or shuffled. When treating layers as frames, layer names don't really make much sense anyway, so perhaps an option to show the layer numbers instead would work better?

Layer insertion is already implemented: right click on a layer and there is a "Insert layer" command which adds a new one above it.

Bucket tool improvements will probably have to wait until after 2.0. Although technically since floodfill results are transmitted as a bitmap, it could be done during the protocol freeze stage of 1.x, but I have no idea how the algorithm in #189 works.

**Comment by blurymind** [comment]
Thank you for adding the changes :)

regarding layer naming - you are right. It would be a better solution if drawpile displayed the frame numbers next to their names, or only display numbers instead of names while in onion skin mode or as an option. It's just a nice usability tweak :)

On the bucket tool - the algorithm in #189 is not open source. We have a better chance of getting this feature from gmic, but thats probably not easy to implement.

**Comment by callaa** [comment]
I added an option to show layer numbers instead of titles. The number starts from zero, so assuming a background layer is used the first layer is number 1.

I think that's about all the features I'm going to implement before 2.0, so I'm closing this issue. New issues can of course be opened for specific animation related features :)

Also, here's something to keep an eye on:
http://www.freedesktop.org/wiki/Specifications/OpenRaster/Draft/MultiplePages/
http://www.freedesktop.org/wiki/Specifications/OpenRaster/Draft/Animation/

One of Krita's kickstarter goals was animation features, so they will be extending the OpenRaster file format to add animation support. Multipage documents seem like the right way to implement frames and the x-sheet docker could be used to manage the pages.

**Comment by blurymind** [comment]
thank you for the work so far! :)

I will keep an eye on 2.0's progress and Krita as well.

But krita is not collaborative like drawpile. It is still at the moment the only collaborative software that can do animation!

**Comment by blurymind** [comment]
The "show numbers" feature does not seem to work for me. It's not acting as a tickbox (enable/disable) and its not showing numbers.

There might be a regression here:
The layer names are gone for some reason. The only way to see the layer's name is to double clicking on it.
![screenshot_2015-06-25_21-56-34](https://cloud.githubusercontent.com/assets/6495061/8363035/24bfc0b0-1b85-11e5-94ef-67c7e5e5d4ce.png)

I however found that deleting drawpile's config file solves this issue.

Why not just show the layer numbers next to their names - as a prefix. And enable the number's when the user is in solo or onion skin mode. I dont think that you need to have it as an entry in the layer menu.

That way you can name your drawings, while being able to also see at what frame they are. You also remove the need to manually do a mandatory step in the workflow - the software can automatically guess when you need to see frame numbers and shouldnt make you enable them manually. You also get one item less in the layers menu - less clutter.

**Comment by callaa** [comment]
Ah, you're right. Looks like the mode selection isn't restored correctly from saved settings.

Prefixing the layer names with the number might be a better way, indeed. I made it toggle between the title and number because I thought it might look confusing with the default naming scheme with the layer numbers at the end.

I prefer the explicit toggle, since some users might like to see the numbers even when not doing animations.

**Comment by blurymind** [comment]
Maybe add an "always show layer numbers" toggle in the "view" menu or in preferences :)

I would love to have them both visible, number-name when animating. That would allow me to mark some of the drawings as key poses.

**Comment by callaa** [comment]
I changed the command into a checkable menu item that toggles whether the titles are prefixed with the index numbers.

**Comment by blurymind** [comment]
sweet! Thank you :)
