### ISSUE TITLE
Finding sessions on local networks (LAN, WiFi, Bluetooth, etc.)

### ISSUE THREAD

**Issue by GreenReaper** [callaa/Drawpile#183]
It would be nice to be able to just run the application and find local machines which are running Drawpile and broadcasting, so you can connect to them. This would ideally use any network available.

This would apply to all networks, although Drawpile works well over Bluetooth, often better than WiFi in cases where the spectrum is too crowded (e.g. the middle of the Zoo at Anthrocon). The bandwidth I got was about 50KB/sec. But users' machines need to be configured to set up a personal area network, which can be a hassle. (Perhaps Drawpile could elevate and do it?)

**Comment by callaa** [comment]
This is something I've been planning for quite a while, but never just got around to it. But now that public session listings are implemented, Drawpile already has the GUI that could be reused for local session discovery too!

So far I've come up with two possible ways to implement it:

* UDP broadcast
* UPnP service discovery. More difficult to implement but perhaps the more modern and standard way. However, I don't know if this works well on Windows.

I'm not sure if its possible to easily integrate Bluetooth support. Qt does have an API for Bluetooth, but apparently it is only supported on Linux and Android.

**Comment by schoerg** [comment]
Use Bonjour to announce.

I would not let Drawpile set up a Bluetooth connection, that is the job of the OS.

**Comment by callaa** [comment]
UPnP/Bonjour would probably be the best solution, since it would work even when Drawpile is running on a non-default port (and all that broadcast business is delegated to the service). My only concern is that many Windows users might not have it installed. Although since iTunes uses Bonjour, it may be safe to assume that enough users have it.

**Comment by GreenReaper** [comment]
Many do, but not all. Personally I disable Bonjour because I don't want services running that I don't use, though I'm probably an exception.

You can also discover an external IP through UPnP, which may be useful when communicating to the user what IP addresses to use (they may or may not want their local address - perhaps offer them the option to try to do UPnP on the server page with a checkbox, and then show the UPnP address).

FWIW Bluetooth PAN on Windows seems to put you on the 169.254.x.x network (presumably because there is no DHCP server on there).

**Comment by schoerg** [comment]
Or you could send advertisements and listen to the broadcast address, as most games do for local network search.

**Comment by callaa** [comment]
That would be the UDP broadcast approach. It has the advantage of not requiring any external dependencies, but has the two rather big drawbacks of needing the server to run on the standard port and me to come up with yet another custom protocol.

I read up a little on UPnP-SD and Zeroconf-SD, and it seems Zeroconf is the better/more widely supported of the two. Now that KDE Frameworks 5 is out, I can use [KDNSSD](http://api.kde.org/frameworks-api/frameworks5-apidocs/kdnssd/html/index.html), which wraps Avahi (on Linux) and Bonjour (on Windows and OSX) behind a nice Qt API. In fact, I got the publishing part (very barebones) working already in just three lines of code!

**Comment by callaa** [comment]
Local server discovery now works on Linux and OSX. Should work on Windows too, but I haven't tested it yet.

**Comment by callaa** [comment]
Now works on Windows too.
