### ISSUE TITLE
No icons since 0.9.9

### ISSUE THREAD

**Issue by hartenfels** [callaa/Drawpile#186]
After upgrading to Drawpile 0.9.9, icons in the application are missing and all the buttons are blank instead. They all worked fine in 0.9.8. I assume it has something to do with the new icon theme introduced in that version.

OS is Lubuntu 14.10. If I use my usual window manager dwm, all icons are missing completely. When using the default window manager LXDE, a few icons are available (new, open, save, undo, redo, copy and paste), but everything else is still missing. The icons aren't the same as they used to be in 0.9.8 either, nor are they the currently selected icon set, I think they're some kind of fallback.

Drawpile is installed via GetDeb. From what I can tell, the light and dark icon sets have been installed in /usr/share/drawpile/drawpile/theme/, Drawpile just isn't using it.

**Comment by callaa** [comment]
Drawpile will use the current system theme icons if available and fall back to the bundled ones if a theme doesn't provide the icon. (Right now, I think only Oxygen and Breeze provide a full icon set)

Are the bundled palettes visible in the palette dock? If not, then it means Drawpile can't find its data directory.
Do you have the "XDG_DATA_DIRS" enviroment variable set? If not, try setting it to "/usr/share". (Qt gets the default search paths from the XDG_* envvars)

If that doesn't work, try opening any SVG file. If the file doesn't open, it means SVG support is missing. (Either it is not compiled in or the Qt SVG library is not installed.)

**Comment by hartenfels** [comment]
It was the last one, I had to install `libqt5svg5`. Now all icons work fine. For completion's sake, the palettes were all visible and setting XDG_DATA_DIRS seems to make no difference.

Is there a separate maintainer of the GetDeb package that I can report this to so that the dependency is added?

Thanks very much for the quick response.

**Comment by callaa** [comment]
Great :)

I don't know who the maintainer is, but I think the contact info is included in the package metadata.
