### ISSUE TITLE
Windows 8.1 Update 1 instant crash

### ISSUE THREAD

**Issue by nobody231** [callaa/Drawpile#199]
When opening Drawpile in Windows 8.1 Update 1, the program immediately crashes. No error code is given.

**Comment by callaa** [comment]
Could be the same problem as in issue #187.
I'm unable to reproduce this bug myself, so more information is needed. (Unfortunately, I'm not very familiar with windows coding, so I'm not sure how to debug this.

**Comment by nobody231** [comment]
I can't give more information! That's all the information given. I'm not too familiar with mainstream languages, I usually use Python.

**Comment by GraphiXS6** [comment]
Same problem.  Instant crash.

**Comment by callaa** [comment]
I'm still not sure what causes the crash, but if it happens before even the main window is shown, the problem is most likely related to incompatible library versions. I just released version 1.0 with updated Qt libraries. I don't know if it fixes the problem, but might be worth a try to see if the new version works.

**Comment by GraphiXS6** [comment]
Hi, thanks Callaa. I believe I had already tried 1.0, to no avail, however,
I downloaded the most recent one on the website, not knowing if it might be
a newer build, or something, and it worked!  I can't verify that it works
on everyone else's system, but worked for me.  So, thanks!  Also, while I
have your attention (and if you'd like me to submit this as an official bug
on the bug tracker, I will) I've been having a difficult time having others
join my sessions/joining sessions created by others.  I created a session
on a computer I have, and then successfully connected to it on another
computer of mine, on the same network (I've also replicated this on a
different set of computers/network).  However, a friend of mine couldn't
connect to it, with him being on a different network.  Then, he created a
session, and no matter what we did, I couldn't connect to that.  I have no
problem, it seems, to connecting to the official sessions hosted on
drawpile, though.  I don't know if it's something to do with the public IP,
and the actual IP, if that makes sense.  Anyway, just thought I'd let you
know.

Keep up the good work. :)

On Sun, Jul 12, 2015 at 11:44 AM, Calle Laakkonen <notifications@github.com>
wrote:

> I'm still not sure what causes the crash, but if it happens before even
> the main window is shown, the problem is most likely related to
> incompatible library versions. I just released version 1.0 with updated Qt
> libraries. I don't know if it fixes the problem, but might be worth a try
> to see if the new version works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/callaa/Drawpile/issues/199#issuecomment-120731488>.
>



-- 
*Caleb Voisine-Addis*
*Artist, Student at Interlochen Arts academy*

**Comment by callaa** [comment]
That's great!

Connection problems like that are typically caused by NAT routers. The new version can use UPnP (which is supported by most home routers) to automatically set up port forwarding and get the public IP address, so that should help a little. Also, in a few days I'll be setting up a public server for people to use if they're unable to host sessions on their own computers.

**Comment by GraphiXS6** [comment]
Awesome!  I have to say, Drawpile seems to have one of the friendliest,
most active dev communities I've seen on a FOSS project.  It's already
quite a nice software, and you just keep improving it.  I wish other
projects were more like it *cough* pencil 2d *cough* 😝  Anyway, I'll be
sure to keep using Drawpile, and I'll report any other bugs I find.
Hopefully, some day I can learn some programming beyond simple Java, and
actually help *debug* some of those bugs.  Anyway.

Cheers!

On Sun, Jul 12, 2015 at 4:02 PM, Calle Laakkonen <notifications@github.com>
wrote:

> That's great!
>
> Connection problems like that are typically caused by NAT routers. The new
> version can use UPnP (which is supported by most home routers) to
> automatically set up port forwarding and get the public IP address, so that
> should help a little. Also, in a few days I'll be setting up a public
> server for people to use if they're unable to host sessions on their own
> computers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/callaa/Drawpile/issues/199#issuecomment-120758217>.
>



-- 
*Caleb Voisine-Addis*
*Artist, Student at Interlochen Arts academy*

**Comment by blurymind** [comment]
ever since animation features were added to drawpile, I notice that some of the peincil2d community has started to move to it eheheh :)
