### ISSUE TITLE
Incompatibility with Mountain Lion 10.8.5 OS X

### ISSUE THREAD

**Issue by fairymonster** [callaa/Drawpile#202]
I was unable to locate any information on the drawpile website about what version of Mac OS X I would need for drawpile. A friend told me though that it was a minimum of 10.7 and I am running Mountain Lion 10.8.5. I've found out another friend with the same version encountered this same issue.

I am successfully able to download drawpile however when I try to open it I receive a message that reads:

"Drawpile cannot be opened because of a problem.: Check with the developer to make sure Drawpile works with this version of OS X. You may need to reinstall the application."

I've rebooted my computer already and tried to reinstall Drawpile but I still encounter the same problem. This goes for both version 9.10 and 9.11.

**Comment by callaa** [comment]
Try starting the application from the terminal to see if it prints out any more error messages. Open a terminal and run:

    /Applications/Drawpile.app/Contents/MacOS/Drawpile

It should print out some debugging information which might help me figure out why it isn't working.

**Comment by fairymonster** [comment]
I opened terminal and told it to run the program with what you gave me and it responded with this:

dyld: Library not loaded: /usr/lib/liblzma.5.dylib
  Referenced from: /Applications/Drawpile.app/Contents/Frameworks/libKF5Archive.5.dylib
  Reason: image not found
Trace/BPT trap: 5 

I hope that helps if you need me to do anything else please let me know. Thanks for getting back to me so quickly I'm really excited about this program.

**Comment by callaa** [comment]
Thanks! Looks like liblzma (a compression library) is not included in that version of OSX. Luckily, this is not a required component, so I made a new build that doesn't link to it. Try if this works: http://drawpile.net/files/osx/Drawpile%200.9.11-2.dmg

**Comment by callaa** [comment]
Hello. Have you tried the new build yet? If so, did it work or are there any new error messages?

**Comment by fairymonster** [comment]
Oh! I'm sorry I guess my message did not go through before! Yes it works wonderfully! No errors or anything thank you!!

**Comment by callaa** [comment]
Great! I'll add a note to the build instructions so I'll remember to maintain compatibility in the future too.
