### ISSUE TITLE
MessageQueue timeout

### ISSUE THREAD

**Issue by EgoEquus** [callaa/Drawpile#204]
Been using the server on Windows. I have been having issues with some clients connecting to long running sessions. The clients on slower Windows machines take so long to join that the server times out with message "MessageQueue timeout QIODevice::write: device not open". Clients on fast machines get connected fast enough to avoid timeout. Is there a change you can make to either load faster or adjust server timeout so it waits for slow clients to initially join? The server is launched with "drawpile-srv.exe --verbose --host-password test1234 --persistent --title HelloArtists"       Thanks!

**Comment by callaa** [comment]
Hello!
This should be fixed already in the current development version. (Commits 0d6cd90 and b1a5b99)
Basically what it does now is manually re-enter the eventloop every 100 ms when handling a large backlog of messages. This ensures the keep-alive pings get sent, even when the program is mostly busy updating the canvas. As a nice side effect, it keeps the UI from locking up too badly at the same time.

**Comment by EgoEquus** [comment]
Oh, that's great. I was afraid I was the only one that had this problem. My artists friends love this app and the server function works great so far.

**Comment by EgoEquus** [comment]
Oh and BTW, I am currently using 0.9.11. So I am assuming this fix will be implemented in a later release.

**Comment by callaa** [comment]
Yes, it will be in the next version, which I'm planning on releasing sometime next month.

**Comment by callaa** [comment]
Version 1.0.0, which should fix this bug, is now out.
