### ISSUE TITLE
Rotate selection (lasso or square)

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#206]
This will be very useful if we want to reuse drawings in an animation workflow, where rotation is key to posing a character. More often than not, when you reuse a drawing, you need to pose it by rotating it on a pivot.

Drawpile can copy and paste a selection, move it and scale it.
What's left now is to be able to also rotate the selection. So instead of redrawing a hand, or an entire head, one can just copy, paste it on the next frame and rotate it.
We would then get massive speed ups in workflow. 

This is not just useful for animation as well. Even on still drawings, being able to rotate a freehand selection allows the artist to tweak the pose of a character - to make it more or less expressive.

**Comment by callaa** [comment]
This is already implemented. Hold Alt and drag to rotate.
I just realized that I haven't documented this anywhere (except the "quick guide to brushes" page.) I'll add it to the shortcuts wiki page for starters.

**Comment by blurymind** [comment]
Would it be possible to add a  widget to rotate the selection, a slider at the tool's properties or some kind of a hint? 
The feature is almost invinsible at the moment. :)

Thank you for implementing it btw. I just hope users discover it.

**Comment by callaa** [comment]
Yeah, a widget would be nice, but it is a bit hard to implement in the current architecture. I'm planning on rewriting the entire canvas view in version 2.0, so it might be possible to implement it then.

**Comment by ionsme** [comment]
Seems like pressing alt shears a selection, rather than rotating it. 
It would be nice to have actual rotation.
Also, it would be nice to be able to specify the point that the selection rotates around. ( like aggie.io )

**Comment by ionsme** [comment]
Ah, I see that you can click the selection to convert to rotation/sheer handles.
It would be a nice addition to be able to select the point that the selection rotates about.
