### ISSUE TITLE
transform tool - uniform scale

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#207]
Holding shift in most applications while scaling results in a uniform scale (x and y scale at the same pace).

Does drawpile have a way to do uniform scale? I cant seem to find it

**Comment by callaa** [comment]
This feature doesn't exist yet. (There is a TODO comment in the code where it would go, though. I don't remember why I haven't implemented this yet.)

**Comment by callaa** [comment]
This is now implemented.

**Comment by blurymind** [comment]
awesome!! :D
