### ISSUE TITLE
idea: transform tool - stamp pixels action, and a pasting in place action.

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#208]
Currently when you lasso select something and you copy and paste it, you can use the transform tool to move the new copy and then clicking away applies the transformation.This unfortunatelly exits the transform tool as its selection is no longer active. 

This can be taken one step further. 
Hitting enter while the transform tool is active could apply the transformed selection's pixels onto the canvas, without exiting the transform tool. In essence acting like a stamp tool. You can continue to move your transformation and hit enter again to stamp its pixels again and so on.

https://www.youtube.com/watch?v=n_gvbkfil0w

**Comment by blurymind** [comment]
Actually the "enter" key is a bad choice for a stamp action, as it is too far from the laft hand.

Alternative ways to stamp the transformation:
- left clicking stamps the pixels  (currently if you left click, it gets erased)
 
Would have been nice to do with spacebar, but that is reserved to panning.

**Comment by blurymind** [comment]
I changed "let click" to right click in previous post. Got it a bit mixed up yesterday.
The idea is to be able to apply the pixels of the active transform selection, without exiting the transform mode. That way you can continue to move/rotate/scale it and continue to apply its pixels in other areas of the canvas or other layers/frames

**Comment by callaa** [comment]
This is very simple to implement, it's just a matter of deciding which button to use.

Inkscape stamps the current selection with spacebar but, as you note, this is used for panning in Drawpile (and GIMP and Krita too.)
Right click is used for dismissing the selection without pasting, so that's taken too.
There aren't many free keys available on the lefthand side, so Enter might be the best option. I can make the shortcut customizable, though.

**Comment by blurymind** [comment]
doesnt "esc" key already cancel selection?

In blender right click applies actions. I guess that is where i got the inspiration from, but blender is perhaps not the best example.

Maybe hold shift, or some of the other modifier keys and left clicking?

I spacebar would have been nice, but it is for panning.

Its best to have it bindable to a shortcut, you are right

**Comment by callaa** [comment]
> doesnt "esc" key already cancel selection?

That would be logical, but apparently it does not! I'll have to add that.

Modifier keys are already in use too, unfortunately. They are used to constrain the shape of the selection when first creating it and when scaling.

I think I'll just use the enter key and make it customizable. (Of course, the default can be changed later too, if a better way is discovered.)

**Comment by blurymind** [comment]
When i make a selection and right click, the selection is dismissed.

when i make a selection, then I move,rotate or scale it, and then right click, in not only dismisses the selection, but it erases the pixels that were  selected - they get deleted.

Is that a bug or intended design?

Can we make it so that  moving, then right clicking stamps.
Selecting and not moving, then right clicking dismisses.

**Comment by blurymind** [comment]
Although it would be beneficial for animation mode to be able to stamp a bunch of selected pixels in the exact same spot in X and Y upon a number of different layers - so having it as a keyboard button and not having to move it in order to stamp .

Would it be possible to also make ctrl+v paste the pixels at the exact same spot they were copied from?

**Comment by callaa** [comment]
Stamping by return key is now implemented.
I also replaced right button with Esc key as the dismiss action.

> When i make a selection, then I move,rotate or scale it, and then right click, it not only dismisses the selection, but it erases all the pixels that were selected and transformed - they get deleted and we get a dismiss action+ lost data (case B)

This is (was) an oversight and not by design. The pixels are erased (and copied to the selection buffer) when the selection is first moved. Dismissing the selection then causes the pixel data to be lost. I changed this so if the selection is dismissed without pasting/stamping, and Undo is sent to cancel the erasure.

Paste-in-place should already work. If the original selection still exists, pasting will create a new selection over the old one.

**Comment by callaa** [comment]
I just realized how the current paste-in-place fails in your use case. Since (non-stamp) pasting will remove the selection, pasting the same image to multiple layers at the same location will be difficult.

**Comment by blurymind** [comment]
So does stamp pasting support paste in place too? I need to try it out tonight :)

**Comment by blurymind** [comment]
Pasting in place is pretty important for the animation workflow.  Thank you for implementing stamping btw!

**Comment by callaa** [comment]
Paste-in-place is now implemented. Rather than adding another menu item, I made the normal *Paste* action smart: if the clipboard image has a source position, it will be used, unless the image would be placed outside the viewport. In that case, the pasted image is centered on the screen.

**Comment by blurymind** [comment]
Just tested it. Thank you so much for this feature! It is incredibly useful and your implementation is very nice. Even better than other software. The stamping works very well
