### ISSUE TITLE
"erase" blending mode for all the brushes, stylus eraser binding to blending modes

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#212]
now that we have "color erase" blending mode, it would make some sense and even be a bit advantageous to have a regular "erase" mode available in all the tools in drawpile that have a blending mode.

One would be able to erase in straight lines, circles and squares. Pixely "pen" tool erasing and antialiased "brush" erasing...

Then a cool option to have is binding the stylus to a blending mode, not just a tool slot.

That way by default the eraser of the tablet stylust can by default be set to "erase" blending mode and the tip to "normal" blending mode.

it would greatly simplify sketching workflow with RGB colors - because we can then use a single tool slot with a brush to both draw with color and color erase the same color without affecting other colors on the canvas.
We dont have to set up two slots for that workflow if the eraser tip of the stylus is set to "color erase"  blending mode of the same slot- same color.

It's just an idea.

**Comment by callaa** [comment]
I think this belongs to issue #201
