### ISSUE TITLE
Assertion failure in paintcore::offsetMask()

### ISSUE THREAD

**Issue by LionsPhil** [callaa/Drawpile#218]
`ASSERT: "xfrac>=0 && xfrac<=1" in file /home/phil/work/Drawpile/src/client/core/brushmask.cpp, line 174`

I was working on the smoother at the time and had some debug in place that shows what stroke co-ordinates were being smoothed:
```
[2015-07-12T15:06:30 WARNING] blending  157 ,  498 
[2015-07-12T15:06:30 WARNING]   with  157 ,  499 
[2015-07-12T15:06:30 WARNING]   with  158 ,  499 
[2015-07-12T15:06:30 WARNING]   with  158 ,  498 
```
(This is the same simple mean averaging as current head, so sum them up and divide through by four.)

It looks like `makeGimpStyleBrushStamp` is the only caller of `offsetMask`, and I can't see how mathematically it can fail to meet this invariant. Might just be an unfortunate floating point rounding quirk or something. :/

**Comment by callaa** [comment]
I've noticed these myself, but the errors happen very rarely. My guess too is that it's caused by floating point rounding. One way to fix it would be to clamp the value, but if the erroneous value is something like 1.000000001, then it really has no other effect than triggering the assert error.

**Comment by callaa** [comment]
I replaced the asserts with warning prints, but they don't seem to trigger, even when the asserts did. Could it be that the value is right at the edge of the floating point precision and (x<1) != !(x>=1)?
In any case, this error won't stop Drawpile anymore.
