### ISSUE TITLE
'Adult' server filtering

### ISSUE THREAD

**Issue by akunim** [callaa/Drawpile#222]
We've noticed that whenever our session gets caught by the 'adult' filter, drive-by traffic stops almost completely. The 'show not suitable content' option seems kind of inconveniently hidden in the preferences menu insomuch that a lot of people don't even know that there are servers being filtered.

I think it would be good to have some sort of indication on the session browser that the adult filter is enabled. 

I do notice in 4afe76b4e70ca6c52c9fad23f9cc170ffadde35a that an explicit 'nsfm' server option is planned, so maybe this is something already taken into consideration.

**Comment by callaa** [comment]
I understand what you mean, the option to not filter the session list is kind of hidden. Here's a mockup of a small change to the session finder dialog that might help:

![session-finder-mockup](https://cloud.githubusercontent.com/assets/464576/8985993/a129ade6-36e2-11e5-95c9-f28a83e2c27c.png)

If any sessions are filtered, a notification text will be shown. Clicking on it will pop up a message box asking whether you want to show the age restricted sessions. (Clicking "Yes" has the same effect as going to the settings dialog and checking the "show NSFM sessions" checkbox.)

This could even be integrated with the OS's parental controls: if "child mode" is active, the option to show R-18 sessions will be disabled.

**Comment by callaa** [comment]
The feature is now implemented. I'll probably release the next version next week or so.
