### ISSUE TITLE
Smudging tool?

### ISSUE THREAD

**Issue by GothorSalvator** [callaa/Drawpile#225]
Don't know if this idea was already proposed or not, but it would be nice for Drawpile to have a smudging tool put in. I tend to pay attention to small details a lot, and I find myself using the smudging tool a lot on other art programs. What if drawpile had a smudging tool as well?

**Comment by callaa** [comment]
Smudging tool is already requested in issue #115, so I'm marking the issue as closed. I'm planning some paint engine improvements for the 2.x series, so a smudging tool is a possibility.
