### ISSUE TITLE
Feature: music player

### ISSUE THREAD

**Issue by sasjakoning** [callaa/Drawpile#228]
Hello!

So ive been around here for quite a while now and a while agao me and some people were talking about how it would be cool if the host of the server would be able to stream music from like, Youtube for the people on the board to hear. options would be for listeners to change volume or turn the music off?

This is just a silly suggestion and really it wont add that much to the program itself.
but hey, why not suggest it. right?

**Comment by blurymind** [comment]
drawpile is not a voip/sound application. I think the developers should focus on making it great at graphics. The feature you suggest is already available in other applications

**Comment by callaa** [comment]
Thanks for the suggestion. However, I feel that a music player is out of scope for this project. Maintaining a streaming music player is really a project of its own. However, there may be improvements that could be done to the chat box to better support such use cases, such as a feature to pin links to audio streams or voice chat rooms, etc.
