### ISSUE TITLE
hard to exit fullscreen mode while play with window tablet(no real keyboard)

### ISSUE THREAD

**Issue by namdoyle** [callaa/Drawpile#251]
because if enter fullscreen mode,window tablet is hard to call the soft keyboard out (possible but cumbersome). i suggest add a gesture to enter and exit fullscreen mode will make life easier.

**Comment by callaa** [comment]
The menubar is (or should be) revealed when the mouse pointer is brought to the top edge of the screen and the fullscreen toggle can be accessed from there. Does this work on your device?

**Comment by namdoyle** [comment]
callaa : OH! THX!!!  i get it !

**Comment by namdoyle** [comment]
Just a suggest :   Can this feature (show up when mouse cursor near) extend to other UI Panel ??

**Comment by callaa** [comment]
I'll see if it can be implemented when I'll start working on the big UI revamp for version 2.1 (probably). A related feature that already exists is that if you float the tool docks, they will remain visible in fullscreen mode too.
