### ISSUE TITLE
Layer visibility and image export

### ISSUE THREAD

**Issue by pachuco** [callaa/Drawpile#259]
When flattening an image, it would be nice if layer visibility were taken into account.
Likewise, when saving ORA, it would be nice if layer visibility was saved with the file.

**Comment by pachuco** [comment]
Oh, I see visibility is indeed stored in 'stack.xml' of ORA file, but not read back on load.

**Comment by callaa** [comment]
Hidden layers are now hidden even in the flattened image.
Loading of the layer visibility flag is now also implemented in the version 2.0 branch.
