### ISSUE TITLE
Canvas Size Spinner Discrepancy

### ISSUE THREAD

**Issue by KurinPawpad** [callaa/Drawpile#264]
I've noticed that when you are resizing the canvas via the 'Resize Canvas' menu (Edit), the spinners only let you type from 0 to 9999, however if you push up/down or pageup/pagedown, you can go higher, to a max hard-limit of 16384x16384 (or any value combination up to 268435456 pixels total dimensions).  It would be nice to be able to manually type in up to the hard-limit.

**Comment by callaa** [comment]
The current maximum value of the spinner seems to be 32767. It is possible to write this in directly, but you have to type it in exactly. Apparently the way the validator works is that if the newly typed in digit would make the value go out of bounds, it will be blocked. (I tried changing the correction mode and it didn't have any effect on the validator.) It seems this is just the way the widget works and changing it will probably be quite difficult.
