### ISSUE TITLE
feature (usability): cross hair cursor/tool icon cursor

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#271]
More often than not it is difficult to see where my own cursor is on the canvas. Drawpile uses a very tiny circle icon to display it and its hard to see it.

I propose adding a crosshair cursor option in preferences. Or an icon of the currently active tool as a cursor.

Mypaint developers had a similar problem. here is how they solved it
https://github.com/mypaint/mypaint/issues/353

https://gna.org/bugs/?20415

**Comment by callaa** [comment]
Doesn't this feature already exist in the View menu?

**Comment by blurymind** [comment]
ah right. You are right. For some reason i thought that it would be in preferences. Close this issue. Sorry
