### ISSUE TITLE
Issue with saving files

### ISSUE THREAD

**Issue by soljak** [callaa/Drawpile#272]
Really loving Drawpile, however myself and a fellow artist are having issues when it come to saving files. Anytime a new document is saved, the program defaults to a previously saved file from months ago in the default Drawpile install folder, even after the new file has been saved as something else.

I've found this is the case on both my newer windows 10 machine as well as my old PC running windows vista.

**Comment by callaa** [comment]
Looks like the last used path was only updated when a file was opened. The fix is now in the stable branch and will be part of the next release.
