### ISSUE TITLE
upnpDiscover has grown a new argument (ttl)

### ISSUE THREAD

**Issue by frispete** [callaa/Drawpile#288]
which results in a build failure similar to:
https://build.opensuse.org/package/live_build_log/home:frispete:graphics/drawpile/openSUSE_Tumbleweed/x86_64
see also:
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/apiversions.txt
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/miniupnpc.h

**Comment by callaa** [comment]
This is already fixed by commit cdd4942.

I'll release the next version some time after Qt 5.6 is released (so next month at the earliest.)
