### ISSUE TITLE
My server won't announce on Drawpile?

### ISSUE THREAD

**Issue by Merleawe** [callaa/Drawpile#291]
I have drawpiles every few weeks with a bunch of art buddies; and normally I'm the one that sets them up and manages them.

However, when I tried to host the one scheduled tonight on the Drawpile server; It would not announce. It even connected to the drawpile server; but it just would NOT announce. When I asked a friend to do it- It announced straight away with what I assume were the exact same settings. I'm considering that it may be an IP ban, but even so I have NO idea why.

I've never shared anything illegal, there has been no abuse in my sessions, and we have NEVER had any adult content in them. Every session we've had is cartoon themed. Any external links we've normally ever shared went to either youtube videos of music/animation, or tumblr posts of art. I REALLY thought I was being careful.

Is it an IP ban? Or is it not? And if so- I want to know why and how I can appeal that case. I can't manage this group without being able to host.

**Comment by callaa** [comment]
There are no IP bans at the moment, so that's not the problem. Does Drawpile show any error message? (I can't recall if I implemented proper error logging. I'll have to improve this in the next release.)
I checked the server logs and didn't see any server errors at least. However, one possible reason its not working might be rate limiting. The server only lets you announce five times (I just increased the limit to 10) per 15 minutes. If this is was the problem, announcement should work again after waiting about 15 minutes.

**Comment by Merleawe** [comment]
Alrighty! Thanks for the feedback. I'll try again today and see if it works this time :)

You are running a great program! Keep up the great work.

**Comment by ClockworkWolf** [comment]
The group that I'm part of experiences the same issue. We run sessions on Fridays and Sundays, usually having to rehost several times through the night.

The standard announcement message will appear and will sometimes announce on the second run (after the 15 min). They can still be joined before then by connecting directly to drawpile.net so connection seems to be fine.

I'm not sure if it's my place to suggest this, but is it possible to increase the limit and rate until it is successfully displayed? From what I've seen the announcement may be sending before the actual connection is made and therefore might not even be seen by the server. If the rate is increased to around one every 15 seconds while the server name is not listed and then revert to the normal 10 per 15 min could that solve the problem without congesting the system?

To mirror Merleawe, thank you for running this; it's an amazing service.

**Comment by callaa** [comment]
I upped the limit to 10 sessions per minute. If the problem still persists, let me know.
