### ISSUE TITLE
Drawpile Translation 

### ISSUE THREAD

**Issue by hacker-owl** [callaa/Drawpile#298]
OK, this is not a issue.
I have done a Chinese translation for Drawpile, but I am a bit lazy to do a pull request.
I personally have tested it. It is acceptable, but not perfect, hope might be helpful.

the ts file is in the zip
[drawpile_zh.zip](https://github.com/callaa/Drawpile/files/136891/drawpile_zh.zip)

**Comment by callaa** [comment]
Thank you! I got your mail too, sorry I didn't respond faster! I added the translation to the stable branch.

**Comment by hacker-owl** [comment]
The file here is the latest version and you may want to remove the emailed version, thank you
