### ISSUE TITLE
Rebinding shortcut doesn't save.

### ISSUE THREAD

**Issue by Nibikibiki** [callaa/Drawpile#302]
I noticed that when you attempt to rebind a shortcut key in Edit>Preferences>Shortcuts, the program does not retain the last rebind command you entered.

Full example:
If I go into Shortcuts and try to rebind Annotations from A to B, click OK to close the Preferences window, the change was not saved. Opening the Shortcuts window shows Annotations has reverted back to A.

If I then assign Annotations from A to B, then assign Brush from B to 1, click OK, Annotations remains rebound to B, but Brush has reverted to being bound to B.

If I then go in and make a series of changes to the shortcut bindings, all of them will stick except the last one.

An odd little problem but something I could duplicate, and had a friend duplicate too.

**Comment by callaa** [comment]
I think what is happening is that the editor widget hasn't closed and thus committed the change when you press Ok. I tried it just now and if I don't close the editor by clicking somewhere else, it doesn't indeed save the change.

**Comment by callaa** [comment]
This is now fixed.
