### ISSUE TITLE
Accidentaly Deleted a tool

### ISSUE THREAD

**Issue by Qazsarea** [callaa/Drawpile#304]
I was drawing and accidental closed the color selection tool. As I can not proceed without, I am desperately trying to find a way to get it back. Please help. All I did was accidently click the x in the corner and reopening drawpile does nothing.

Thank you, please get back to me asap

**Comment by callaa** [comment]
Go to View menu and the Docks submenu, and there click on the first menu entry (the one with the name of the current tool.) This should restore the dock.
