### ISSUE TITLE
Not being able to build it on ubuntu 14.04 and related distros

### ISSUE THREAD

**Issue by Wahffle** [callaa/Drawpile#314]
I'm new to building software from source on linux so I'm almost 100% sure I did something wrong, but there's already an issue relating problems while building drawpile on ubuntu 14.04 I decided to specify the error I got while trying to do it.

I'm currently using an updated version of elementary os freya 0.3.2, based on ubuntu 14.04.

First I installed these dependencies: "qtbase5-dev libgif-dev cmake g++ build-essential git libqt5svg5-dev qtmultimedia5-dev" along with manually installing KArchieve 5.10 from the kde library

I download the 1.0.2 sourcecode from the website and extracted it on my home page, then I did 
**cd "drawpile directory"
mkdir build && cd build
cmake ..
make && sudo make install**

And I was presented with the following error while doing this:

**[ 93%] Building CXX object src/client/CMakeFiles/drawpile.dir/drawpile_automoc.cpp.o
In file included from /home/pancake/drawpile-1.0.2/build/src/client/drawpile_automoc.cpp:2:0:
/home/pancake/drawpile-1.0.2/build/src/client/moc_color_dialog.cpp:199:10: error: ‘ColorWheel’ has not been declared
         &ColorWheel::staticMetaObject,
          ^
make[2]: *** [src/client/CMakeFiles/drawpile.dir/drawpile_automoc.cpp.o] Error 1
make[1]: *** [src/client/CMakeFiles/drawpile.dir/all] Error 2
make: *** [all] Error 2**

A curious thing is that I also tried manually installing QtColorPicker before, using the same method as above, and I also got the exact same error. So is this error related to using QtColorPicker (since Drawpile comes with a bundled version) on ubuntu 14.04 and related distros or did I do something wrong?

**Comment by callaa** [comment]
Try the latest stable-1.x branch version. This error should be fixed there.
