### ISSUE TITLE
Default canvas size cannot be larger than display resolution

### ISSUE THREAD

**Issue by Psarius** [callaa/Drawpile#317]
Drawpile remembers the resolution of the last canvas you create, and sets that as the default whenever you open up the program again. It will also remember that size when you click the 'New' button too.

However, it only seems to do the latter in 1.0.2 if the size chosen is larger than the monitor resolution (or, at least, 1920x1080, which is the resolution of my monitor.) If it's larger, then it defaults to the display resolution.

_Making a new canvas, with the size smaller than the display._
![drawpile_2016-04-03_21-52-29](https://cloud.githubusercontent.com/assets/18134601/14238467/8167a31a-f9e6-11e5-8471-21200437a70c.png)

_The resolution of the canvas after opening a new instance of drawpile._
![drawpile_2016-04-03_21-52-50](https://cloud.githubusercontent.com/assets/18134601/14238469/83409fac-f9e6-11e5-8b2b-f113356d7cbc.png)

_Making a new canvas, with the size larger than display._
![drawpile_2016-04-03_21-48-50](https://cloud.githubusercontent.com/assets/18134601/14238419/fcf90b78-f9e5-11e5-9cde-b49bed79f100.png)

_The resolution of the canvas after opening a new instance of drawpile._
![drawpile_2016-04-03_21-49-13](https://cloud.githubusercontent.com/assets/18134601/14238420/0017693a-f9e6-11e5-84c1-b15c40718ffa.png)

**Comment by callaa** [comment]
This was an intentional feature to prevent excessively large canvas opening by default, but upon further consideration, using the screen size as the maximum is indeed a bit too small. I changed the limit to a fixed maximum size of 65536x65536 pixels.
