### ISSUE TITLE
Unable to view sessions on Drawpile.net

### ISSUE THREAD

**Issue by beeppeep** [callaa/Drawpile#318]
Recently every time I go to the Drawpile webpage and go to see the serves this is what comes up.

![dp error](https://cloud.githubusercontent.com/assets/18272179/14263782/942ed974-fa8a-11e5-81f1-faae0d4056c7.png)

This only just started a day or so ago, before that it was fine, I could view and access all of the servers listed. I'm not sure if this is happening to me specifically or that there is something wrong with the site.

If anyone can tell me why this is happening/how to fix it or if there is another way to view the servers I'd really appreciate it!!

**Comment by callaa** [comment]
Whoops, look like I broke it when I tried to force the listing to use HTTPS only. It's fixed now, thanks for letting me know!
