### ISSUE TITLE
New paint engine suggestion

### ISSUE THREAD

**Issue by hankcs** [callaa/Drawpile#323]
Dear develop community,

Hello,

I have a suggestion for a new paint engine. 

Why not consider [libmypaint](https://github.com/mypaint/libmypaint)? It is the brush engine used by the famous apps like MyPaint and Krita. And it is a self-contained C library so quite easy to use.

What's more, there is a libmypaint integration for QT based applications [qtmypaint](https://github.com/feeef/qtmypaint):
![](https://github.com/zhangxiang2014/QTLibmypaint/raw/master/show.png)

**Comment by callaa** [comment]
Integrating the Mypaint engine is an often requested feature and something I want to try to during the 2.x series. The difficulty is that its not designed for use in a collaborative application (it might work just fine without modification, its just not designed for it) so there are few features that are slightly problematic. (E.g. everything that uses random numbers.)

**Comment by hankcs** [comment]
Oh, yes. I understand your meaning now. Integrating the Mypaint engine means to modifying package protocols.

I will try a simple protocols which simply synchronizes pixel changes but not the mouse movements.

Thank you for explaining.
