### ISSUE TITLE
Request: stabilizer

### ISSUE THREAD

**Issue by erik90mx** [callaa/Drawpile#332]
Hi there

Well... like the title, an stabilizer feature to help us to draw.
maybe you can use the Krita ones?

https://phabricator.kde.org/diffusion/KRITA/browse/master/libs/ui/tool/kis_tool_freehand_helper.cpp

Greetings

**Comment by blurymind** [comment]
I already posted this a year ago :)

**Comment by callaa** [comment]
Duplicate of issue #179.
Sorry it's taking so long. I'll take another look at trying to understand how the stabilizer algorithm works after I get the version 2.0 beta out.
