### ISSUE TITLE
Ubuntu GetDeb page doesn't have Drawpile anymore.

### ISSUE THREAD

**Issue by remeranAuthor** [callaa/Drawpile#334]
http://www.getdeb.net/install/drawpile 
http://www.getdeb.net/app/DrawPile

Returns an error that could not find package drawpile.

**Comment by callaa** [comment]
I don't make any distro specific packages, so this is not something I can do anything about. However, I will provide distro-agnostic binary packages as soon as Flatpak or Snap mature enough to be usable. I've experimented with Flatpak a little and it seems quite promising.

**Comment by callaa** [comment]
Version 1.0.3 is now released and available as an AppImage. In the future, I will provide new releases as Flatpaks as well.
