### ISSUE TITLE
flipbook - ability to set play range

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#336]
Right now the flipbook always plays frames 2 to the last frame.

When animating very often we tend to set a play range - in order to figure out if an animation works ok.
So it would be nice if the flipbook could have two new input boxes:

play from: 5
to: 8

so for example we can then play the animation from layer 5 to layer 8, when we have 16 frames of animation

**Comment by callaa** [comment]
This is now implemented and will be part of the next release (1.0.3)

**Comment by blurymind** [comment]
@callaa You are incredibly fast. Thank you so much for improving the animation features! :)

Btw I've been active on the opentoonz bug tracker and recently a user implemented quite a nice stroke stabilizer.

I thought that perhaps you might be interested in his approach - as this is something you might be looking into the future:
https://github.com/opentoonz/opentoonz/issues/81
He shared the code here:
https://github.com/opentoonz/opentoonz/pull/432

Opentoonz is a c++ / QT animation application that is open source. They might have a lot of professional animation features, but they dont have the animchat features of drawpile. Drawpile seems to be in a league of it's own at the moment - as there in no open source or proprietary software out there that can do that!

Perhaps we should coin the word 'Animchat' and use it on the website and description of the software - it will draw more the attention of the animation community to drawpile!
