### ISSUE TITLE
Animation - Ability to export animated gif image 

### ISSUE THREAD

**Issue by blurymind** [callaa/Drawpile#340]
Since drawpile's current aim is to be used for simple but fun animations made during animchat sessions,
it would be cool if it could also let the user easily export that animation as an easy to share to the web animated gif image. :)

something that can be posted to tumblr or twitter right away.  Here is an example of an animation group that is thriving on gifs like that:
http://sonicrunninglikeanidiot.tumblr.com/

**Comment by callaa** [comment]
Drawpile already has support for exporting animated GIFs, although the output quality is not the best. GIF support is included in the Windows and OSX binary packages. On Linux, GIFLIB must be installed when when compiling to include the feature.

**Comment by blurymind** [comment]
ah Sorry. I totally overlooked it. I found the option after installing giflib! Sorry for the false alarm
