### ISSUE TITLE
Remote drawpile server problem

### ISSUE THREAD

**Issue by kjhdgaidos** [callaa/Drawpile#344]
Whenever I try to enter or host a board, using the remote drawpile.net server, this message pops up https://i.gyazo.com/7820cc1b39132a4e6b0c72c9c82ff835.png I'm not sure what it means or how to fix it

**Comment by callaa** [comment]
Recently, the server's SSL certificate expired and I had to generate a new one. Go to the *Known hosts* tab in the *Preferences* dialog and remove *drawpile.net* from the list. You should then be able to log in again.

**Comment by kjhdgaidos** [comment]
@callaa Thank you!
