### ISSUE TITLE
Whenever I try to host a server, an error comes up with "could not connect to server, connection refused"

### ISSUE THREAD

**Issue by LadyLilligant** [callaa/Drawpile#347]
it was working the other day with my friend so I'm confused why its not working now
![untitled](https://cloud.githubusercontent.com/assets/20632435/17088596/ec8fc600-51e2-11e6-94f6-1c0e225bc0b9.png)

**Comment by callaa** [comment]
The server had shut down and didn't autorestart for some reason. I started it manually and it is now up again.
