### ISSUE TITLE
when trying to host, when it worked beofre, i get "could not connect to server" "session is closed"

### ISSUE THREAD

**Issue by LadyLilligant** [callaa/Drawpile#348]
![untitled](https://cloud.githubusercontent.com/assets/20632435/17163660/30f7bb40-5387-11e6-9d69-adc99d75354f.png)

**Comment by callaa** [comment]
That error is caused by the server being full. I updated the code to show the right error message in this case.

The current limit at drawpile.net is 20 simultaneous sessions, but I think the server can handle a bit more. I'll increase the limit and see how it fares.
