### ISSUE TITLE
Brush Tool crippled

### ISSUE THREAD

**Issue by soulmage** [callaa/Drawpile#350]
The last month, ever since I tried re-downloading Drawpile to try to get around the (now fixed) server issues, the primary brush tool has not worked.  At first I thought it was not working at all, but after some experimentation I found that it _does_ draw normally on the bottom-most layer, provided there is already a 'base' color to draw on top of (a simple white fill tool on the canvas works).  But given that most group chats have the bottom layer locked (for obvious reasons), that doesn't help much.  The pencil, watercolor and eraser tools still work normally so far as I can tell.
This does not appear to be an issue with my tablet, as the problem persists if I use my mouse instead, and I have tried re-installing the program several times.
Thank you for your time, I hope this can be resolved soon.

**Comment by callaa** [comment]
Is your brush blending mode set to something other than "Normal" or "Behind"? The other blending modes need a base color to work on.

**Comment by soulmage** [comment]
Took me a little while to figure out what you were referring to, but I found it and oh my goodness I'm so embarrassed!  Thank you so very much; I really enjoy Drawpile and this has been driving me crazy!

**Comment by callaa** [comment]
No problem, glad you got it working :)
