### ISSUE TITLE
drawpile 2.0 server listing

### ISSUE THREAD

**Issue by pachuco** [callaa/Drawpile#356]
Requesting that drawpile.net list servers for 2.0 clients. This way you get no shortage of testing.

**Comment by pachuco** [comment]
>Once 2.0 stabilizes enough to become the new default, the public server will be switched over to it.

Disregard OP post, I can't read.

**Comment by pachuco** [comment]
Actually, I have a better idea. have another server for the beta.

**Comment by callaa** [comment]
The listing does work when used inside the app, but it might indeed be a good idea to show them on the web page as well.

I'm currently working on a new server software that should address some of the shortcomings the current one has when used as a public server (such as the high memory consumption.) When it's ready for testing, I'll put it on drawpile.net along with the current 1.0 server.

**Comment by callaa** [comment]
The beta server is now up at `drawpile.net:27751` and version 2.0 announcements are included in the default listing.
