### ISSUE TITLE
Layers disappeared

### ISSUE THREAD

**Issue by TheGreatMizuti** [callaa/Drawpile#359]
New Drawpile user here. Hopefully this wasn't already addressed elsewhere, but I was using Drawpile for some sketching practice and the layers disappeared. I tried going into the view/docks/layers, and while the layers dock appears on the side, it is empty and doesn't allow me to add any layers. I tried closing it out, reopning the file, creating a new file, but the layers just don't show up. Not even the default background/foreground layers appear. Help please!

**Comment by callaa** [comment]
Can you take a screenshot of what Drawpile looks like when you create a new blank file?

**Comment by TheGreatMizuti** [comment]
Yup!

http://i1244.photobucket.com/albums/gg580/Mizuti/dpscreenshot_zpsjivwr8eq.png

**Comment by callaa** [comment]
It kind of looks like the layer dock has somehow maximized under the brush dock. Try if detaching and redocking the brush dock will fix it. (The brush dock can be dragged and moved from its tab-bar.)

**Comment by TheGreatMizuti** [comment]
Ah, perfect! Worked like a charm! Thank you very much, I appreciate the help! :)
