### ISSUE TITLE
Server access and hosting

### ISSUE THREAD

**Issue by Polotno** [callaa/Drawpile#360]
Recently Ive noticed that i cant host remote server anymore. 
DP shows message "Your ip adress is banned from this server"

And I cant join some servers. DP shows same message  "Your ip adress is banned from this server"

Ive tried my friend server(he did not ban me or anything). And still I get this message.

Is that thing is forever now? Is it ban for me on Drawpile remote hosting system?

**Comment by callaa** [comment]
Bans are server specific. Your friend is probably hosting the session on drawpile.net and not their own server. If haven't done anything to warrant a ban, then most likely you've either inherited an IP address from a user who did or are sharing it with one. (E.g. if your ISP is using carrier grade NAT, the latter is a distinct possibility.)

Send me a mail with your IP address, and I'll take a look. In any case, the IP bans aren't forever, I remove them after a while.

**Comment by Polotno** [comment]
Thanks a lot for answer. But I guess I'll wait for a some time. Maybe its better to endure punishment. 8)

**Comment by callaa** [comment]
I've now removed all bans older than one week.
