### ISSUE TITLE
Query: is support for drawing on video/frames feasible?

### ISSUE THREAD

**Issue by kwill** [callaa/Drawpile#361]
How likely/feasible is support for drawing on video (or a sequence of numbered images), in addition to drawing on a single image?

In other words, the foundation for functionality similar to http://www.tweaksoftware.com/products/rv and similar tools.

I don't know how similar this query is to https://github.com/callaa/Drawpile/issues/275 (which seems to be about *creating* a series of frames).

**Comment by callaa** [comment]
Drawpile has basic support for animated images by using layers to represent layers. Animated GIFs can be opened and each frame will be loaded as a layer. Better animation support may be implemented in the future.
