### ISSUE TITLE
[2.0b1] Crash'n'burn while drawing, other issues along the way

### ISSUE THREAD

**Issue by pachuco** [callaa/Drawpile#362]
I hosted server and had friend join over. Drawn a little bit(minutes of no drawing followed by seconds of drawing) using 'Brush'. 'Disconnect' followed by crash and dump ensues.
[friend] ah it said disconnected and connection refused.

This archive contains dump and log for crash.
https://a.pomf.cat/hkzqll.zip

If it helps, I host server, resize canvas to 2000x2000, have friend join

**Comment by pachuco** [comment]
Forgot to mention. OS is Win XP x86.

**Comment by pachuco** [comment]
My friend had some miscellaneous join problems along the way.
[friend] said "invalid state" the last few times then it worked

**Comment by pachuco** [comment]
Also misc issue, I am unable to rename layers.

**Comment by pachuco** [comment]
Input smoothing didn't work until I dragged it to 0 and back to max.

**Comment by pachuco** [comment]
In this time order.
- I notice red loading lines in status bar at one point. These add up as I draw.
- My friend draws stuff.
- My client disconnects from own server and friend's client is too. I rehost.
- Friend complains the stuff he drew doesn't appear in the playback.

**Comment by pachuco** [comment]
Also, client doesn't remember window maximization status when switching between fullscreen(F11) and windowed.

**Comment by pachuco** [comment]
I moved layer around in list. Disconnected, crash.
https://files.catbox.moe/afu4oc.zip crash and dump log.

**Comment by pachuco** [comment]
Playing back dprec postmortem. I am impressed by 2 beta's performance. And not locking up interface.
Here are odd things I noticed:
- Any chat by host appears as "User #1" and he don't appear in user list. This is later remedied by a rehost.
- I see friend's name duplicated in user list at one point.
- Friend's deletions don't seem to work. I asked him of tool he used for deletions, it's the "square marker".
- Playback finished, I have 3 of my friend's nick in user list, and one of mine.


The .dprec file is available via request, due to NSFW and private nature.

**Comment by callaa** [comment]
Thanks for reporting! I'll look into these.

**Comment by pachuco** [comment]
[Server] Session size limit reached.
[Server] Session size limit reached.
*** You have been kicked by

Followed by crash.
https://files.catbox.moe/7nc2sc.zip

**Comment by pachuco** [comment]
I used paint bucket to accidentally fill whole canvas. Both me and friend got above message and got kicked. No crash, rehosted.

**Comment by pachuco** [comment]
2nd friend reports not being able to join for 'connection refused'. I launch 2nd 2.0b1 client and try to join localhost.
I leave and rehost, try localhost join a couple of times. Hosting client dies.
https://files.catbox.moe/3sh46c.zip

**Comment by pachuco** [comment]
Adding another symptom to layer drag'n'drop reordering.
I init drawing with multiple layers, drag them around, everything is ok.

I host server without anybody joining. As soon as I drag, I am disconnected from it, no crash.
This is repeatable.
As variations, I draw before and after hosting, before doing a layer drag. Same result.

**Comment by callaa** [comment]
Thanks again for reporting. Beta 2 is now out, and I think I managed to fix all (or at least most) of these bugs.
