### ISSUE TITLE
Playback cut off at halfway point?

### ISSUE THREAD

**Issue by Rockmanan** [callaa/Drawpile#365]
I was drawing with a friend yesterday and we both hit record session. We drew for quite a while (roughly 7 hrs), and were excited to watch the playback. On trying to save out the session recording, the earlier record session when joining feature didn't seem to work, and on recording fresh, only grabbed the feed as if we'd started recording just at the end. We may have used it incorrectly, in which case, more explanation on how to use session recording properly (possibly a basic step by step?) on the Drawpile website would be appreciated. 

After this, we tried joining the session again to grab the recording from the load feed, which has worked fine in the past. However, when both of us tried joining, the feed began around 1/2 way into the session, and we lost about 3+ hours of feed. Neither of us disconnected during the session, and we could not figure out why this happened. Is there a limit to how long a feed will record? Is this a bug? Is there something we can do to avoid feed loss in the future?

Thank you for your help!

**Comment by callaa** [comment]
When you check the "record session" checkbox in the join dialog, Drawpile will select a filename based on the session ID and put it in folder selected in the preferences dialog. (The default is the My Documents folder, if I recall correctly.) This should allow you to record the entire session.

When you start recording with the action from the File menu, Drawpile will save the history from the beginning if it still has it in memory. In case of a long session, there may no longer be a clean starting point in memory, so the program will create a new starting point from the current canvas state.

Check the "Animation" tab in the preferences dialog. The "Default folder" text box has the location where the automatically started recording will be placed. If the directory exists, Drawpile should have created a file there. If the file exists but Drawpile cannot open it, can you send me a copy? (Even a partial one will do. E.g. just the first 100KB will help me figure out what's wrong with it.)

**Comment by Rockmanan** [comment]
Thank you so much for the response! I didn't realize it was saving on exit correctly, but I was able to find the intact file exactly where you directed! Thank you so much!! I can't wait to tell my drawing partner <3

**Comment by callaa** [comment]
Glad to hear the recording was OK :) I also updated the recording help page on the website. It's now up to date with the current version and a bit easier to read.
