### ISSUE TITLE
[Linux] [1.0.4] Drawpile locks task managers on server connect

### ISSUE THREAD

**Issue by notfood** [callaa/Drawpile#366]
Archlinux distro
Drawpile version 1.0.4-1
Plasma desktop

There seems to be a problem with Drawpile after connecting to remote. It always locks the task managers. I tested with a newly created user. Plasma 5, Openbox, Fluxbox. Their task managers all hang whenever Drawpile connects to a server, it is fine until that point.

I can kill the plasmashell and restart it but even after that, it is very sluggish and unresponsible. Drawpile is the only program causing this. Could it be spamming something to the task manager?

This doesn't happen with the beta (2.0.0b1)

**Comment by pachuco** [comment]
How big is the session you are joining?
Does this also happen when joining a fresh drawing session? Do things return to normal after joining?

In windows, I have problems with shell GUI(I am using bblean instead of explorer) locking up while joined session is playing back. It comes back to normal after either session is done playing or timeout occurs.

**Comment by notfood** [comment]
It continues to lock even after playback is done.
The playback I was testing with was tiny and neglegible.
journalctl doesn't show any errors, not even after killing the taskmanager.

**Comment by notfood** [comment]
I installed kdocker and ran drawpile through it. It doesn't lock the taskbar anymore but I noticed it spams kdocker with "drawpile: Untitled* - The Board Title" a lot of times per second, no wonder it was locking the taskbar.

**Comment by notfood** [comment]
Perfect! It doesn't lock any GUI on load playing anymore.

Thank you. Consider it closed for me.

**Comment by callaa** [comment]
Great! This explains why the 2.0 beta performed better, even though it uses the same tricks to avoid locking up the main thread for too long. (2.0 has a slightly different architecture and only calls setWindowModified when the value changes.) There's still room for improvement, mainly moving the paint engine to a background thread. I tried implementing it once already, but encountered too many concurrency problems, and so decided to postpone that work for later.
