### ISSUE TITLE
Donate to the project?

### ISSUE THREAD

**Issue by Rockmanan** [callaa/Drawpile#375]
I wanted to know if there is a way to donate to the drawpile devs? I am having so much fun with drawpile and its clear how much work has gone into the project. I would like to give back what I can! However, I can't find a way to donate! Am I missing a donation link somewhere? 

Thank you for all your hard work!!

**Comment by callaa** [comment]
Thank you for your offer! Unfortunately, as the law here in Finland currently stands, I cannot solicit donations without a special permit. So things like Kickstarter or Patreon are currently not possible for me.
