### ISSUE TITLE
The overtaking of sessions and overloading the server by randos who want to advertise themselves

### ISSUE THREAD

**Issue by DerangedBones** [callaa/Drawpile#376]
Hello

New issue has popped up in regards to hosting. A person called "BaileyAdams" has opened up numerous sessions with no real intent on drawing. All they do is make a session and make is so that no one can join, so that they can advertise their youtube channel. I think theyre 12 or something.

Anyway, it would be great to have some way of closing sessions that have been up with no one in them. at this point theyve been up for days, and are making it hard or impossible for others to make sessions. 

thanks

**Comment by callaa** [comment]
An idle time limit is now in place on the public server. I notice he still has a couple of listings with an uptime of over 21 days, but those seem to be on his own server, so at least they're not hogging any shared resources. If listing spam starts to get out of hand, I'll try to improve the limiting features on the listing server.
