### ISSUE TITLE
Locking the UI tools layout

### ISSUE THREAD

**Issue by EsperHubb** [callaa/Drawpile#378]
As the title suggest, there needs to be a way to lock the UI for tools so that they doesn't get misplaced or dragged from their original desired positions.

I have had a few cases where I had to re configure my setup because of the PC picking up a click on my tablet when trying to select different colors or using the navigator.

**Comment by callaa** [comment]
I added a new option in the "Docks" submenu that will lock all the docks in their places, preventing them from being moved or closed. This feature will be in the soon-to-be-released version 1.0.6.
