### ISSUE TITLE
Lock Cut, Paste & Fill not working with re-joined Session Operator

### ISSUE THREAD

**Issue by erik90mx** [callaa/Drawpile#379]
DrawPile v 1.0.5
Windows 8.1 64bits

**Required**
-Have 2 or more session operators
-Activate the Lock Cut, Paste & Fill function 
---(Just the Session Operators are able to use those tools)--

**REPRODUCE BUG**
-One of the Session Operators left the session
-The same user re-join to the session
-The user is assigned to be Session Operator by the other aviable Session Operator 
---The new assigned Session Operator can't Cut, Paste, Fill or Delete layers---

**USER WORKAROUND TO MAKE IT WORK**
-The new assigned Session Operator have to disable the Lock Cut, Paste & Fill function
-The new assigned Session Operator have to re-enable the Lock Cut, Paste & Fill function
(Have to make an unexpected toggle of the funtion)
---IT WORKS NOW--

**Comment by callaa** [comment]
Thanks for reporting! The fix is now implemented and will be part of the 1.0.6 release soon.
