### ISSUE TITLE
Rethinking OP

### ISSUE THREAD

**Issue by callaa** [callaa/Drawpile#387]
With the 2.0 release nearing, I think it's a good time to rethink some old features.
Namely: how do users get session operator status.

Prior to version 0.9.2, a user could gain OP by:

 * Hosting a new session
 * Being the senior user in a session when its only OP leaves
 * Joining a persistent session with no users
 * Being granted the status by another operator.

The server enforces that there must be at least one operator in a session, even if
its just some random member. The reason for this was that there were no other ways
of gaining OP status. If the last operator left the session, that was it. The session
would have been operatorless from then on.

However, right now Drawpile supports a couple of alternative methods of gaining OP:

 * Logging in with a moderator account
 * Using the /opword

Until version 2.0 is finished, there is no need to care about backward compatibility, so now is the perfect time to break things.

Let's consider various use cases:

## Usecase: Ad-hoc session with the built-in server

In this case, the session is running on the hosting user's computer and will go away when
said user leaves. It is natural, that the host has (permanent?) operator status.
In this case, I don't see any need for rules more complicated than:

 * Permanent OP for host (i.e. user connected from localhost)
 * Other users can be granted OP as usual
 * No other rules needed

## Usecase: Public free-for-all session

Users are coming and going and there is no-one official in charge of the session.

 * Initial user has OP status
 * Users can be granted OP as usual
 * OK to give random users OP if there is no-one else around

## Usecase: Public session

A session that runs on a public server, but is moderated by one or more people. (Not necessarily the owner of the server.)

 * Initial user has OP status
 * Users can be granted OP as usual
 * A way of identifying users is required
 * Automatically granting OP to random users is not desirable
 
 The problem here is that on a public server, user authentication is not available (except perhaps for serverwide moderators.)
 Currently, the /opword methods does that. But is there a better way?
 
 ## Usecase: Private session
 
 A long running session that runs on a private server with user authentication
 
 * Initial user has OP status
 * Users can be granted OP as usual
 * Server can remember which users have OP and automatically grant it when they log in again
 * Automatically granting OP to random users may not be desirable
 
## User identification

For private servers, using registered user accounts is a simple way of proving that a user is
who they claim to be.

For public servers, there is no single best way. Internally, the server could remember the IP address
associated with a specific username. However someone could still log in to the same server with
the same username and prevent the real user from joining and regaining OP. Also, due to NAT,
there may be multiple users sharing the same IP address. (Although this is becoming less of a
problem thanks to IPv6)

Another solution would be to use tripcodes. This approach suffers from the same problem that the username can be blocked by someone else.
However, it might be a nice feature to have anyway, as it's a simple way of proving your identity.

It seems like the Opword is still the most practical solution for public sessions. This feature could be promoted to first class status by exposing it in the GUI.

## Summary

This could be the new ruleset:

 * Local user gets permanent OP in the built-in server
 * User who hosts a session gets OP by default
 * OP status of authenticated users is remembered and restored when logging back in
 * /opword may still be the best solution for public sessions
 * If no other way of regaining op exists (no authenticated users, no opword): OP is granted automatically to a random user
 
Any comments or ideas or other use cases?

**Comment by GraphiXS6** [comment]
I think that 'accounts' would be good, where they login credentials are stored on a server, and when you join a server you have an ability to choose a name and join like you do now, or login, and it pings the server to see if they have mod status on the server?  I don't know how difficult that would be to code, but that's just my 2 cents.

**Comment by erik90mx** [comment]
@callaa 

the Next case scenarios: 

*********
++User A don't know about opword command++
-User A make a public session (by Default is granted with OP status, NO opword setup)
-User B come in and stay afk in the session.
-User A left the session.
-User B is the new OP of the session (afk or just messing with sessions)
-User A come in again to the session (now he is not the OP)
-The session has not an "active" OP 

*********
A HARD TROLL CASE
-User A make a public session (by Default is granted with OP status, he setup a opword)
-User B come in and stay afk
-User A left the session
-User B is now the OP of the session
-User A come in again
-Meanwhile User A is loading the log history, User B kick him from the server. (or before he type the password)
-User B repeats his action each time User A try to come in.
*********
For that cases I can just think in some solutions:
+Make the opword an option avaiable in the GUI from the host session window (initial setup obligatory?)
+In the join session form, add the opword textfield (optional), and send that info to the session (avoiding the premature kick of a valid OP)
+A OP can't kick another OP inmediatly after their status change (make a timeout before can do it)

I hope this can be helpful.
Greetings

**Comment by callaa** [comment]
Good point about the hard troll case. Version 2.0 now supports in session bans, so it's even harder because the troll can just ban all the previous ops. Therefore, it's important to be able to stop them from getting op status in the first place. One thing that will help here is that the server would not auto-op anyone if the opword (or authenticated ops) is available.

**Comment by callaa** [comment]
I've now implemented the following changes to the way operator status is granted:

 * Authenticated users who were operators when they left are automatically re-opped when they log back in to a session
 * Moderators are excluded from the above rule, since they always have OP status and may just be visiting a session
 * If a session can regain an operator (i.e. opword is set or an authenticated user is remembered,) the server will allow the session to be without an operator and will not not auto-op random users.

Other than that, the rules are the same as before.
