### ISSUE TITLE
Cannot Connect to Server on Same internet

### ISSUE THREAD

**Issue by Uluri** [callaa/Drawpile#392]
I will host my drawpile on the site, but other computers also using my internet cannot connect to the server. We all can connect to other people's drawpiles, and others can connect to us, but our household cannot connect to each other in the household. This is true for any of us trying to host the session. This issue happens with both Private and Public session types. In a Private session, one is not prompted to input a password and are just stuck in limbo with that session for a while. 

I would like to be able to draw together with those in my house, but I don't know what it is we need to do to fix the problem.

**Comment by digitalcircuit** [comment]
It sounds like your router doesn't properly handle hairpin NAT, i.e. requests going from your network out to the Internet and back into your network.  There's some more (admittedly technical) details here:  https://serverfault.com/questions/55611/loopback-to-forwarded-public-ip-address-from-local-network-hairpin-nat

To work around it, you can try having others sharing your household's Internet connect to your local computer's IP address.  You should be able to find that in the network connection status window, [or by typing `ipconfig` in a Command Prompt](https://lifehacker.com/5833108/how-to-find-your-local-and-external-ip-address ).

I'm not one of the Drawpile devs, so if this doesn't work, I could be overlooking something and it might be worthwhile waiting for an official reply :)

**Comment by callaa** [comment]
This is most likely a firewall problem.Most firewalls are by default configured to silently drop incoming connections, which results in the program appearing to be stuck in limbo.

When connecting to a server on the same network, try connecting directly to their local IP address. If UPnP is not enabled in the preferences dialog, the address will appear in the status bar at the lower right corner of the screen. (For internal IPs, it should be 192.something or 10.something)

If everyone is using a Mac, the local server is announced with Bonjour and can be found in the "Nearby" section of the find sessions dialog.

**Comment by Uluri** [comment]
Thank you guys, doing the IP thing helped. We are able to connect now! Super thank you.
