### ISSUE TITLE
2.0 doesn't launch - incompatible dlls?

### ISSUE THREAD

**Issue by powermeep** [callaa/Drawpile#393]
Windows 7 64bit
Unpacked Drawpile2 archive into 1.06 installation directory.

Running drawpile-2.0b2.exe yields the following error:
"The procedure entry point _ZN12QtConcurrent18BlockSizeManagerV213timeAfterUserEv could not be located in the dynamic link library Qt5Concurrent.dll"

Runnint drawpile-srv-2.0b2.exe yields the following error:
"The procedure entry point _ZN10QJsonArray7detach2Ej could not be located in the dynamic link library Qt5Core.dll"

Does 2.0 use updated versions of these files? I noticed there weren't new versions in the download. I also suspect that it crashed at the first error and there will be more errors once it gets past these ones.

Attached are the versions of the dlls I have.
[Current DLLs.zip](https://github.com/callaa/Drawpile/files/737673/Current.DLLs.zip)

**Comment by callaa** [comment]
Those DLLs seem to be different than what's in the 1.0.6 package. (Or at least, what *should* be in the package.) They could be left over from a previous version. Try uninstalling, then reinstalling. (At least, a fresh reinstall worked when I tried it.)

**Comment by powermeep** [comment]
Yeah, my bad. I assumed I was using the latest version but never actually double checked. I had 1.0.2 installed. Updated to 1.0.6, dropped the 2.0 stuff in and everything worked perfectly.
