### ISSUE TITLE
No way back from full screen mode on tablet device

### ISSUE THREAD

**Issue by GreenReaper** [callaa/Drawpile#61]
The full screen mode is great, but if you don't have a keyboard, it doesn't seem to be possible to return from it. Adding a few buttons at the side of the chat window would help - return to windowed mode, maybe a miniature palette selector, possibly some file controls.

**Comment by callaa** [comment]
The menu bar is now shown when the pointer is brought to the top edge of the screen. From there, the user can return to windowed mode.
